import "server-only";
import { randomUUID } from "crypto";
import type { BrandRecord } from "@/lib/db/types";
import { integrationMode, type IntegrationMode } from "@/lib/env";
import { serverEnv } from "@/lib/env/server";
import { getSupabaseServiceClient } from "@/lib/supabase/server";
import { persistentDevelopmentStore } from "@/lib/development/persistent-store";
type Store = { brands: BrandRecord[] };
export type BrandInput = Omit<BrandRecord, "id" | "createdAt">;
function store(): Store { return persistentDevelopmentStore("brands", () => ({ brands: [] })); }
function toBrand(row: Record<string, unknown>): BrandRecord { return { id: String(row.id), name: String(row.name || ""), slug: String(row.slug || ""), description: row.description ? String(row.description) : undefined, logoUrl: row.logo_url ? String(row.logo_url) : undefined, websiteUrl: row.website_url ? String(row.website_url) : undefined, authorizationNote: row.authorization_note ? String(row.authorization_note) : undefined, status: String(row.status || "draft") as BrandRecord["status"], seoTitle: row.seo_title ? String(row.seo_title) : undefined, seoDescription: row.seo_description ? String(row.seo_description) : undefined, createdAt: String(row.created_at) }; }
export async function listAdminBrands(query = ""): Promise<BrandRecord[]> { const mode = integrationMode(serverEnv.supabaseServiceConfigured); const search = query.trim().toLowerCase(); if (mode === "mock") return store().brands.filter((item) => !search || [item.name, item.slug, item.description, item.websiteUrl, item.status].join(" ").toLowerCase().includes(search)); if (mode === "unconfigured") throw new Error("Brand storage is not configured."); const client = getSupabaseServiceClient(); if (!client) throw new Error("Supabase service client is unavailable."); const { data, error } = await client.from("brands").select("*").order("name").limit(200); if (error) throw new Error("Could not load brands."); return (data || []).map((row) => toBrand(row as Record<string, unknown>)); }
export async function createAdminBrand(input: BrandInput): Promise<{ brand: BrandRecord; mode: IntegrationMode }> { const mode = integrationMode(serverEnv.supabaseServiceConfigured); if (mode === "unconfigured") throw new Error("Brand storage is not configured."); if (mode === "mock") { if (store().brands.some((item) => item.slug === input.slug)) throw new Error("A brand already uses this URL slug."); const brand = { ...input, id: randomUUID(), createdAt: new Date().toISOString() }; store().brands.push(brand); return { brand, mode }; } const client = getSupabaseServiceClient(); if (!client) throw new Error("Supabase service client is unavailable."); const { data, error } = await client.from("brands").insert({ name: input.name, slug: input.slug, description: input.description || null, logo_url: input.logoUrl || null, website_url: input.websiteUrl || null, authorization_note: input.authorizationNote || null, status: input.status, seo_title: input.seoTitle || null, seo_description: input.seoDescription || null }).select("*").single(); if (error || !data) throw new Error("Could not create the brand."); return { brand: toBrand(data as Record<string, unknown>), mode }; }
export async function updateAdminBrand(id: string, patch: Partial<BrandInput>): Promise<BrandRecord | null> { const mode = integrationMode(serverEnv.supabaseServiceConfigured); if (mode === "mock") { const index = store().brands.findIndex((item) => item.id === id); if (index < 0) return null; const brand = { ...store().brands[index], ...patch }; store().brands[index] = brand; return brand; } if (mode === "unconfigured") throw new Error("Brand storage is not configured."); const client = getSupabaseServiceClient(); if (!client) throw new Error("Supabase service client is unavailable."); const update = { ...(patch.name !== undefined ? { name: patch.name } : {}), ...(patch.slug !== undefined ? { slug: patch.slug } : {}), ...(patch.description !== undefined ? { description: patch.description || null } : {}), ...(patch.logoUrl !== undefined ? { logo_url: patch.logoUrl || null } : {}), ...(patch.websiteUrl !== undefined ? { website_url: patch.websiteUrl || null } : {}), ...(patch.authorizationNote !== undefined ? { authorization_note: patch.authorizationNote || null } : {}), ...(patch.status !== undefined ? { status: patch.status } : {}), ...(patch.seoTitle !== undefined ? { seo_title: patch.seoTitle || null } : {}), ...(patch.seoDescription !== undefined ? { seo_description: patch.seoDescription || null } : {}) }; const { data, error } = await client.from("brands").update(update).eq("id", id).select("*").maybeSingle(); if (error) throw new Error("Could not update the brand."); return data ? toBrand(data as Record<string, unknown>) : null; }
export async function permanentlyDeleteAdminBrand(id: string): Promise<boolean> { const mode = integrationMode(serverEnv.supabaseServiceConfigured); if (mode === "mock") { const index = store().brands.findIndex((item) => item.id === id && item.status === "archived"); if (index < 0) return false; store().brands.splice(index, 1); return true; } if (mode === "unconfigured") throw new Error("Brand storage is not configured."); const client = getSupabaseServiceClient(); if (!client) throw new Error("Supabase service client is unavailable."); const { data, error } = await client.from("brands").delete().eq("id", id).eq("status", "archived").select("id"); if (error) throw new Error("Could not permanently delete the archived brand."); return Boolean(data?.length); }
