import "server-only";
import { randomUUID } from "crypto";
import type { CatalogueCategoryRecord } from "@/lib/db/types";
import { integrationMode, type IntegrationMode } from "@/lib/env";
import { serverEnv } from "@/lib/env/server";
import { getSupabaseServiceClient } from "@/lib/supabase/server";
import { persistentDevelopmentStore } from "@/lib/development/persistent-store";
type Store = { categories: CatalogueCategoryRecord[] };
export type CatalogueCategoryInput = Omit<CatalogueCategoryRecord, "id" | "createdAt">;
function store(): Store { return persistentDevelopmentStore("categories", () => { const createdAt = new Date().toISOString(); return { categories: [
  { id: "hvac-cold", name: "HVAC / Cold Insulation", slug: "hvac-cold", description: "Insulation approaches for HVAC, chilled water, refrigeration and condensation control.", sortOrder: 1, status: "published", createdAt },
  { id: "hot-insulation", name: "Hot Insulation", slug: "hot-insulation", description: "Materials for hot process services, utility lines, equipment and thermal protection.", sortOrder: 2, status: "published", createdAt },
  { id: "acoustic-insulation", name: "Acoustic Insulation", slug: "acoustic-insulation", description: "Sound absorption, isolation and vibration-management materials and assemblies.", sortOrder: 3, status: "published", createdAt },
  { id: "roof-peb-underdeck", name: "Roof & PEB Underdeck Insulation", slug: "roof-peb-underdeck", description: "Roof, metal deck and pre-engineered building insulation systems.", sortOrder: 4, status: "published", createdAt },
  { id: "water-tank-cover", name: "Water Tank Cover", slug: "water-tank-cover", description: "Custom-fitted reflective insulation covers for water-storage tanks.", sortOrder: 5, status: "published", createdAt },
] }; }); }
function toCategory(row: Record<string, unknown>): CatalogueCategoryRecord { return { id: String(row.id), parentId: row.parent_id ? String(row.parent_id) : undefined, name: String(row.name || ""), slug: String(row.slug || ""), description: row.description ? String(row.description) : undefined, imageUrl: row.image_url ? String(row.image_url) : undefined, sortOrder: Number(row.sort_order || 0), status: String(row.status || "draft") as CatalogueCategoryRecord["status"], seoTitle: row.seo_title ? String(row.seo_title) : undefined, seoDescription: row.seo_description ? String(row.seo_description) : undefined, createdAt: String(row.created_at) }; }
export async function listAdminCategories(query = ""): Promise<CatalogueCategoryRecord[]> { const mode = integrationMode(serverEnv.supabaseServiceConfigured); const search = query.trim().toLowerCase(); if (mode === "mock") return store().categories.filter((item) => !search || [item.name, item.slug, item.description, item.status].join(" ").toLowerCase().includes(search)).sort((a, b) => a.sortOrder - b.sortOrder); if (mode === "unconfigured") throw new Error("Category storage is not configured."); const client = getSupabaseServiceClient(); if (!client) throw new Error("Supabase service client is unavailable."); const { data, error } = await client.from("categories").select("*").order("sort_order").limit(200); if (error) throw new Error("Could not load categories."); return (data || []).map((row) => toCategory(row as Record<string, unknown>)); }
export async function createAdminCategory(input: CatalogueCategoryInput): Promise<{ category: CatalogueCategoryRecord; mode: IntegrationMode }> { const mode = integrationMode(serverEnv.supabaseServiceConfigured); if (mode === "unconfigured") throw new Error("Category storage is not configured."); if (mode === "mock") { if (store().categories.some((item) => item.slug === input.slug)) throw new Error("A category already uses this URL slug."); const category = { ...input, id: randomUUID(), createdAt: new Date().toISOString() }; store().categories.push(category); return { category, mode }; } const client = getSupabaseServiceClient(); if (!client) throw new Error("Supabase service client is unavailable."); const { data, error } = await client.from("categories").insert({ parent_id: input.parentId || null, name: input.name, slug: input.slug, description: input.description || null, image_url: input.imageUrl || null, sort_order: input.sortOrder, status: input.status, seo_title: input.seoTitle || null, seo_description: input.seoDescription || null }).select("*").single(); if (error || !data) throw new Error("Could not create the category."); return { category: toCategory(data as Record<string, unknown>), mode }; }
export async function updateAdminCategory(id: string, patch: Partial<CatalogueCategoryInput>): Promise<CatalogueCategoryRecord | null> { const mode = integrationMode(serverEnv.supabaseServiceConfigured); if (mode === "mock") { const index = store().categories.findIndex((item) => item.id === id); if (index < 0) return null; const category = { ...store().categories[index], ...patch }; store().categories[index] = category; return category; } if (mode === "unconfigured") throw new Error("Category storage is not configured."); const client = getSupabaseServiceClient(); if (!client) throw new Error("Supabase service client is unavailable."); const update = { ...(patch.parentId !== undefined ? { parent_id: patch.parentId || null } : {}), ...(patch.name !== undefined ? { name: patch.name } : {}), ...(patch.slug !== undefined ? { slug: patch.slug } : {}), ...(patch.description !== undefined ? { description: patch.description || null } : {}), ...(patch.imageUrl !== undefined ? { image_url: patch.imageUrl || null } : {}), ...(patch.sortOrder !== undefined ? { sort_order: patch.sortOrder } : {}), ...(patch.status !== undefined ? { status: patch.status } : {}), ...(patch.seoTitle !== undefined ? { seo_title: patch.seoTitle || null } : {}), ...(patch.seoDescription !== undefined ? { seo_description: patch.seoDescription || null } : {}) }; const { data, error } = await client.from("categories").update(update).eq("id", id).select("*").maybeSingle(); if (error) throw new Error("Could not update the category."); return data ? toCategory(data as Record<string, unknown>) : null; }
export async function permanentlyDeleteAdminCategory(id: string): Promise<boolean> { const mode = integrationMode(serverEnv.supabaseServiceConfigured); if (mode === "mock") { const index = store().categories.findIndex((item) => item.id === id && item.status === "archived"); if (index < 0) return false; store().categories.splice(index, 1); return true; } if (mode === "unconfigured") throw new Error("Category storage is not configured."); const client = getSupabaseServiceClient(); if (!client) throw new Error("Supabase service client is unavailable."); const { data, error } = await client.from("categories").delete().eq("id", id).eq("status", "archived").select("id"); if (error) throw new Error("Could not permanently delete the archived category."); return Boolean(data?.length); }
