import "server-only";

import { randomUUID } from "crypto";
import { catalogue } from "@/lib/catalogue";
import { integrationMode, type IntegrationMode } from "@/lib/env";
import { serverEnv } from "@/lib/env/server";
import type { ProductMasterRecord, ProductPublicationStatus } from "@/lib/db/types";
import { getSupabaseServiceClient } from "@/lib/supabase/server";
import { persistentDevelopmentStore } from "@/lib/development/persistent-store";

type Store = { products: ProductMasterRecord[] };
function store(): Store {
  return persistentDevelopmentStore("products", () => {
    const createdAt = new Date().toISOString();
    return { products: [
      ...catalogue.map((item) => ({ id: item.slug, name: item.name, slug: item.slug, shortDescription: item.shortDescription, overview: item.overview, material: item.family, category: item.category, family: item.family, imageUrl: item.image, quotationEnabled: ["xlpe-sheet-insulation", "xlpe-tube-insulation", "nitrile-rubber-sheet", "nitrile-rubber-tube", "insulation-adhesive", "insulation-tapes"].includes(item.slug), featured: ["nitrile-rubber-sheet", "xlpe-sheet-insulation", "xlpe-underdeck-insulation", "foil-bubble-insulation", "rock-wool-slab", "glass-wool-acoustic-board"].includes(item.slug), active: true, status: "published" as const, createdAt })),
      { id: "open-cell-nitrile-rubber-sheet", name: "Open Cell Nitrile Rubber Sheet", slug: "open-cell-nitrile-rubber-sheet", shortDescription: "Open-cell elastomeric sheet insulation for acoustic and technical applications.", material: "Elastomeric foam", category: "Acoustic insulation", family: "Elastomeric foam", quotationEnabled: true, featured: false, active: true, status: "draft" as const, createdAt },
    ] };
  });
}
export type ProductMasterInput = Omit<ProductMasterRecord, "id" | "createdAt">;
function toProduct(row: Record<string, unknown>): ProductMasterRecord { const specs = (row.specifications || {}) as Record<string, unknown>; return { id: String(row.id), name: String(row.name || ""), slug: String(row.slug || ""), shortDescription: row.short_description ? String(row.short_description) : undefined, overview: row.description ? String(row.description) : undefined, material: row.material ? String(row.material) : undefined, category: specs.category ? String(specs.category) : undefined, family: specs.family ? String(specs.family) : undefined, formFactor: row.form_factor ? String(row.form_factor) : undefined, imageUrl: specs.imageUrl ? String(specs.imageUrl) : undefined, quotationEnabled: Boolean(row.quotation_enabled), featured: Boolean(row.featured), active: Boolean(row.active), status: row.status as ProductPublicationStatus, createdAt: String(row.created_at) }; }
function slugify(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "").slice(0, 90) || "product"; }
export async function listAdminProducts(query = ""): Promise<ProductMasterRecord[]> { const mode = integrationMode(serverEnv.supabaseServiceConfigured); const search = query.trim().toLowerCase(); if (mode === "mock") return store().products.filter((item) => !search || [item.name, item.slug, item.shortDescription, item.material, item.category, item.family].join(" ").toLowerCase().includes(search)); if (mode === "unconfigured") throw new Error("Product storage is not configured."); const client = getSupabaseServiceClient(); if (!client) throw new Error("Supabase service client is unavailable."); let request = client.from("products").select("*").order("created_at", { ascending: false }).limit(200); if (query.trim()) request = request.or(`name.ilike.%${query.trim()}%,slug.ilike.%${query.trim()}%,short_description.ilike.%${query.trim()}%,material.ilike.%${query.trim()}%`); const { data, error } = await request; if (error) throw new Error("Could not load products."); return (data || []).map((row) => toProduct(row as Record<string, unknown>)); }
export async function createAdminProduct(input: ProductMasterInput): Promise<{ product: ProductMasterRecord; mode: IntegrationMode }> { const mode = integrationMode(serverEnv.supabaseServiceConfigured); if (mode === "unconfigured") throw new Error("Product storage is not configured."); const slug = input.slug || slugify(input.name); if (mode === "mock") { if (store().products.some((item) => item.slug === slug)) throw new Error("A product already uses this URL slug."); const product = { ...input, slug, id: randomUUID(), createdAt: new Date().toISOString() }; store().products.unshift(product); return { product, mode }; } const client = getSupabaseServiceClient(); if (!client) throw new Error("Supabase service client is unavailable."); const { data, error } = await client.from("products").insert({ name: input.name, slug, short_description: input.shortDescription || null, description: input.overview || null, material: input.material || null, form_factor: input.formFactor || null, specifications: { category: input.category || "", family: input.family || "", imageUrl: input.imageUrl || "" }, quotation_enabled: input.quotationEnabled, featured: input.featured, active: input.active, status: input.status, published_at: input.status === "published" ? new Date().toISOString() : null }).select("*").single(); if (error || !data) throw new Error("Could not create the product."); return { product: toProduct(data as Record<string, unknown>), mode }; }
export async function updateAdminProduct(id: string, patch: Partial<ProductMasterInput>): Promise<ProductMasterRecord | null> { const mode = integrationMode(serverEnv.supabaseServiceConfigured); if (mode === "mock") { const index = store().products.findIndex((item) => item.id === id); if (index < 0) return null; const product = { ...store().products[index], ...patch, active: patch.active === undefined ? store().products[index].active : patch.active }; store().products[index] = product; return product; } if (mode === "unconfigured") throw new Error("Product storage is not configured."); const client = getSupabaseServiceClient(); if (!client) throw new Error("Supabase service client is unavailable."); const update = { ...(patch.name !== undefined ? { name: patch.name } : {}), ...(patch.shortDescription !== undefined ? { short_description: patch.shortDescription || null } : {}), ...(patch.overview !== undefined ? { description: patch.overview || null } : {}), ...(patch.material !== undefined ? { material: patch.material || null } : {}), ...(patch.formFactor !== undefined ? { form_factor: patch.formFactor || null } : {}), ...(patch.quotationEnabled !== undefined ? { quotation_enabled: patch.quotationEnabled } : {}), ...(patch.featured !== undefined ? { featured: patch.featured } : {}), ...(patch.active !== undefined ? { active: patch.active } : {}), ...(patch.status !== undefined ? { status: patch.status, published_at: patch.status === "published" ? new Date().toISOString() : null, archived_at: patch.status === "archived" ? new Date().toISOString() : null } : {}) }; const { data, error } = await client.from("products").update(update).eq("id", id).select("*").maybeSingle(); if (error) throw new Error("Could not update the product."); return data ? toProduct(data as Record<string, unknown>) : null; }
