import "server-only";

import { randomUUID } from "crypto";
import type { SiteContentRecord } from "@/lib/db/types";
import { integrationMode, type IntegrationMode } from "@/lib/env";
import { serverEnv } from "@/lib/env/server";
import { getSupabaseServiceClient } from "@/lib/supabase/server";
import { persistentDevelopmentStore } from "@/lib/development/persistent-store";

type Store = { content: SiteContentRecord[] };
export type SiteContentInput = Omit<SiteContentRecord, "id" | "createdAt" | "updatedAt" | "publishedAt">;

function store(): Store {
  return persistentDevelopmentStore("site-content", () => {
    const timestamp = new Date().toISOString();
    const create = (contentKey: string, title: string, body: Record<string, unknown>) => ({ id: contentKey, contentKey, title, body, status: "published" as const, createdAt: timestamp, updatedAt: timestamp, publishedAt: timestamp });
    return { content: [
      create("homepage.hero", "Homepage hero", { eyebrow: "INSULATE. OPTIMISE. PERFORM.", heading: "Engineered insulation solutions for better performance.", description: "Advanced thermal, acoustic and industrial insulation solutions for HVAC, commercial, industrial and infrastructure projects.", primaryCta: "Explore products", secondaryCta: "Request a quote" }),
      create("company.profile", "Company profile", { name: "RAC INSUTECH", address: "Rukhmini Niwas, Near Vrundavan Garden Appt. Behind Tulshan Bungalow, Geeta Nagar, Akola", phone: "9130958594", email: "racinsutech@gmail.com", website: "www.racinsutech.com", gstin: "27AKLPL9475H1ZH", state: "27-Maharashtra" }),
      create("homepage.quote_cta", "Homepage quotation CTA", { heading: "Ready to optimise efficiency and performance?", description: "Share your insulation requirement and RAC will help route the right technical conversation.", ctaLabel: "Request a quote" }),
      create("about.company", "About RAC", { heading: "Practical insulation support for project-led decisions.", description: "RAC Insutech supports HVAC, acoustic, thermal and industrial insulation requirements with product guidance, quotation support and documentation." }),
    ] };
  });
}

function toContent(row: Record<string, unknown>): SiteContentRecord { return { id: String(row.id), contentKey: String(row.content_key || ""), title: row.title ? String(row.title) : undefined, body: (row.body || {}) as Record<string, unknown>, status: String(row.status || "draft") as SiteContentRecord["status"], seoTitle: row.seo_title ? String(row.seo_title) : undefined, seoDescription: row.seo_description ? String(row.seo_description) : undefined, publishedAt: row.published_at ? String(row.published_at) : undefined, createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }
export async function listAdminSiteContent(query = ""): Promise<SiteContentRecord[]> { const mode = integrationMode(serverEnv.supabaseServiceConfigured); const search = query.trim().toLowerCase(); if (mode === "mock") return store().content.filter((item) => !search || [item.contentKey, item.title, JSON.stringify(item.body), item.status, item.seoTitle, item.seoDescription].join(" ").toLowerCase().includes(search)); if (mode === "unconfigured") throw new Error("Content storage is not configured."); const client = getSupabaseServiceClient(); if (!client) throw new Error("Supabase service client is unavailable."); let request = client.from("site_content").select("*").order("updated_at", { ascending: false }).limit(200); if (query.trim()) request = request.or(`content_key.ilike.%${query.trim()}%,title.ilike.%${query.trim()}%,seo_title.ilike.%${query.trim()}%`); const { data, error } = await request; if (error) throw new Error("Could not load website content."); return (data || []).map((row) => toContent(row as Record<string, unknown>)); }
export async function createAdminSiteContent(input: SiteContentInput): Promise<{ content: SiteContentRecord; mode: IntegrationMode }> { const mode = integrationMode(serverEnv.supabaseServiceConfigured); if (mode === "unconfigured") throw new Error("Content storage is not configured."); if (mode === "mock") { if (store().content.some((item) => item.contentKey === input.contentKey)) throw new Error("This content key already exists."); const timestamp = new Date().toISOString(); const content = { ...input, id: randomUUID(), createdAt: timestamp, updatedAt: timestamp, publishedAt: input.status === "published" ? timestamp : undefined }; store().content.unshift(content); return { content, mode }; } const client = getSupabaseServiceClient(); if (!client) throw new Error("Supabase service client is unavailable."); const { data, error } = await client.from("site_content").insert({ content_key: input.contentKey, title: input.title || null, body: input.body, status: input.status, seo_title: input.seoTitle || null, seo_description: input.seoDescription || null, published_at: input.status === "published" ? new Date().toISOString() : null }).select("*").single(); if (error || !data) throw new Error("Could not create the content record."); return { content: toContent(data as Record<string, unknown>), mode }; }
export async function updateAdminSiteContent(id: string, patch: Partial<SiteContentInput>): Promise<SiteContentRecord | null> { const mode = integrationMode(serverEnv.supabaseServiceConfigured); if (mode === "mock") { const index = store().content.findIndex((item) => item.id === id); if (index < 0) return null; const now = new Date().toISOString(); const content = { ...store().content[index], ...patch, updatedAt: now, publishedAt: patch.status === "published" ? store().content[index].publishedAt || now : patch.status === "archived" ? undefined : store().content[index].publishedAt }; store().content[index] = content; return content; } if (mode === "unconfigured") throw new Error("Content storage is not configured."); const client = getSupabaseServiceClient(); if (!client) throw new Error("Supabase service client is unavailable."); const update = { ...(patch.contentKey !== undefined ? { content_key: patch.contentKey } : {}), ...(patch.title !== undefined ? { title: patch.title || null } : {}), ...(patch.body !== undefined ? { body: patch.body } : {}), ...(patch.status !== undefined ? { status: patch.status, published_at: patch.status === "published" ? new Date().toISOString() : null } : {}), ...(patch.seoTitle !== undefined ? { seo_title: patch.seoTitle || null } : {}), ...(patch.seoDescription !== undefined ? { seo_description: patch.seoDescription || null } : {}) }; const { data, error } = await client.from("site_content").update(update).eq("id", id).select("*").maybeSingle(); if (error) throw new Error("Could not update website content."); return data ? toContent(data as Record<string, unknown>) : null; }
export async function permanentlyDeleteAdminSiteContent(id: string): Promise<boolean> { const mode = integrationMode(serverEnv.supabaseServiceConfigured); if (mode === "mock") { const index = store().content.findIndex((item) => item.id === id && item.status === "archived"); if (index < 0) return false; store().content.splice(index, 1); return true; } if (mode === "unconfigured") throw new Error("Content storage is not configured."); const client = getSupabaseServiceClient(); if (!client) throw new Error("Supabase service client is unavailable."); const { data, error } = await client.from("site_content").delete().eq("id", id).eq("status", "archived").select("id"); if (error) throw new Error("Could not permanently delete the archived content record."); return Boolean(data?.length); }
