import "server-only";

import { randomUUID } from "crypto";
import { integrationMode, type IntegrationMode } from "@/lib/env";
import { serverEnv } from "@/lib/env/server";
import type { ProductVariantRecord } from "@/lib/db/types";
import { quotationVariants } from "@/lib/quotations/catalogue";
import { getSupabaseServiceClient } from "@/lib/supabase/server";
import { persistentDevelopmentStore } from "@/lib/development/persistent-store";

type Store = { variants: ProductVariantRecord[] };
const productMasterId: Record<string, string> = { "xlpe-sheet": "xlpe-sheet-insulation", "xlpe-tube": "xlpe-tube-insulation", "nitrile-rubber-sheet": "nitrile-rubber-sheet", "open-cell-nitrile-rubber-sheet": "open-cell-nitrile-rubber-sheet", "nitrile-rubber-tube": "nitrile-rubber-tube", "nitrile-rubber-tube-class-1": "nitrile-rubber-tube", "insulation-tape": "insulation-tapes", "insulation-adhesive": "insulation-adhesive" };
function store(): Store { return persistentDevelopmentStore("variants", () => ({ variants: quotationVariants.map((item) => ({ id: item.id, productId: productMasterId[item.productId] || item.productId, name: `${item.materialClass} | ${item.thickness} | ${item.lamination}`, thickness: item.thickness, dimensions: item.size, materialClass: item.materialClass, lamination: item.lamination, rollAreaM2: item.rollAreaM2, tubesPerCarton: item.packTubes, tubeLengthMm: item.tubeLength ? Number(item.tubeLength.match(/\d+/)?.[0] || 0) || undefined : undefined, packRunningMetres: item.packRunningMetres, active: true, createdAt: new Date().toISOString() })) })); }
export type ProductVariantInput = Omit<ProductVariantRecord, "id" | "createdAt">;
function toVariant(row: Record<string, unknown>): ProductVariantRecord { const number = (value: unknown) => value === null || value === undefined ? undefined : Number(value); return { id: String(row.id), productId: String(row.product_id), name: String(row.name || ""), sku: row.sku ? String(row.sku) : undefined, thickness: row.thickness ? String(row.thickness) : undefined, dimensions: row.dimensions ? String(row.dimensions) : undefined, density: row.density ? String(row.density) : undefined, materialClass: row.material_class ? String(row.material_class) : undefined, lamination: row.lamination ? String(row.lamination) : undefined, widthM: number(row.width_m), lengthM: number(row.length_m), rollAreaM2: number(row.roll_area_m2), tubeLengthMm: number(row.tube_length_mm), tubesPerCarton: number(row.tubes_per_carton), packRunningMetres: number(row.pack_running_metres), active: Boolean(row.active), createdAt: String(row.created_at) }; }
export async function listAdminVariants(query = ""): Promise<ProductVariantRecord[]> { const mode = integrationMode(serverEnv.supabaseServiceConfigured); const search = query.trim().toLowerCase(); if (mode === "mock") return store().variants.filter((item) => !search || [item.productId,item.name,item.sku,item.thickness,item.dimensions,item.materialClass,item.lamination].join(" ").toLowerCase().includes(search)); if (mode === "unconfigured") throw new Error("Variant storage is not configured."); const client = getSupabaseServiceClient(); if (!client) throw new Error("Supabase service client is unavailable."); const { data,error }=await client.from("product_variants").select("*").order("created_at",{ascending:false}).limit(300);if(error)throw new Error("Could not load variants.");return(data||[]).map((row)=>toVariant(row as Record<string,unknown>)); }
export async function createAdminVariant(input: ProductVariantInput): Promise<{ variant: ProductVariantRecord; mode: IntegrationMode }> { const mode=integrationMode(serverEnv.supabaseServiceConfigured);if(mode==="unconfigured")throw new Error("Variant storage is not configured.");if(mode==="mock"){if(store().variants.some((item)=>item.productId===input.productId&&item.name.toLowerCase()===input.name.toLowerCase()))throw new Error("This product already has a variant with the same name.");const variant={...input,id:randomUUID(),createdAt:new Date().toISOString()};store().variants.unshift(variant);return{variant,mode}}const client=getSupabaseServiceClient();if(!client)throw new Error("Supabase service client is unavailable.");const{data,error}=await client.from("product_variants").insert({product_id:input.productId,name:input.name,sku:input.sku||null,thickness:input.thickness||null,dimensions:input.dimensions||null,density:input.density||null,material_class:input.materialClass||null,lamination:input.lamination||null,width_m:input.widthM||null,length_m:input.lengthM||null,roll_area_m2:input.rollAreaM2||null,tube_length_mm:input.tubeLengthMm||null,tubes_per_carton:input.tubesPerCarton||null,pack_running_metres:input.packRunningMetres||null,active:input.active}).select("*").single();if(error||!data)throw new Error("Could not create the variant.");return{variant:toVariant(data as Record<string,unknown>),mode} }
export async function updateAdminVariant(id:string,patch:Partial<ProductVariantInput>):Promise<ProductVariantRecord|null>{const mode=integrationMode(serverEnv.supabaseServiceConfigured);if(mode==="mock"){const index=store().variants.findIndex((item)=>item.id===id);if(index<0)return null;const variant={...store().variants[index],...patch};store().variants[index]=variant;return variant}if(mode==="unconfigured")throw new Error("Variant storage is not configured.");const client=getSupabaseServiceClient();if(!client)throw new Error("Supabase service client is unavailable.");const update={...(patch.name!==undefined?{name:patch.name}:{}),...(patch.sku!==undefined?{sku:patch.sku||null}:{}),...(patch.thickness!==undefined?{thickness:patch.thickness||null}:{}),...(patch.dimensions!==undefined?{dimensions:patch.dimensions||null}:{}),...(patch.density!==undefined?{density:patch.density||null}:{}),...(patch.materialClass!==undefined?{material_class:patch.materialClass||null}:{}),...(patch.lamination!==undefined?{lamination:patch.lamination||null}:{}),...(patch.widthM!==undefined?{width_m:patch.widthM||null}:{}),...(patch.lengthM!==undefined?{length_m:patch.lengthM||null}:{}),...(patch.rollAreaM2!==undefined?{roll_area_m2:patch.rollAreaM2||null}:{}),...(patch.tubeLengthMm!==undefined?{tube_length_mm:patch.tubeLengthMm||null}:{}),...(patch.tubesPerCarton!==undefined?{tubes_per_carton:patch.tubesPerCarton||null}:{}),...(patch.packRunningMetres!==undefined?{pack_running_metres:patch.packRunningMetres||null}:{}),...(patch.active!==undefined?{active:patch.active}:{})};const{data,error}=await client.from("product_variants").update(update).eq("id",id).select("*").maybeSingle();if(error)throw new Error("Could not update the variant.");return data?toVariant(data as Record<string,unknown>):null}
