"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ArrowRight, BriefcaseBusiness, CalendarDays, Edit3, MapPin, Plus, Search, X } from "lucide-react";
import { usePathname, useRouter } from "next/navigation";
import { adminFetch } from "@/lib/auth/admin-client";
import type { CustomerRecord, ProjectRecord, ProjectStatus } from "@/lib/db/types";

const statuses: ProjectStatus[] = ["active", "on_hold", "completed", "archived"];
type ProjectDraft = Omit<ProjectRecord, "id" | "slug" | "createdAt">;
type ProjectDetail = { project: ProjectRecord; linked: { enquiries: number; quotations: number } };

export default function AdminProjectsPanel() {
  const pathname = usePathname(); const router = useRouter(); const [records, setRecords] = useState<ProjectRecord[]>([]); const [customers, setCustomers] = useState<CustomerRecord[]>([]); const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [selected, setSelected] = useState<ProjectDetail | null>(null); const [compose, setCompose] = useState(false); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  const load = useCallback(async () => { const [projectResponse, customerResponse] = await Promise.all([adminFetch("/api/admin/projects"), adminFetch("/api/admin/customers")]); const projects = await projectResponse.json() as { projects?: ProjectRecord[]; message?: string }; const customerData = await customerResponse.json() as { customers?: CustomerRecord[] }; setRecords(projects.projects || []); setCustomers(customerData.customers || []); if (!projectResponse.ok) setMessage(projects.message || "Could not load projects."); setLoading(false); }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { if (pathname.endsWith("/new")) { const timer = window.setTimeout(() => setCompose(true), 0); return () => window.clearTimeout(timer); } }, [pathname]);
  const customerName = useCallback((customerId?: string) => { const customer = customers.find((item) => item.id === customerId); return customer ? customer.company || customer.fullName : "Customer not linked"; }, [customers]);
  const filtered = useMemo(() => records.filter((item) => (status === "all" || item.projectStatus === status) && [item.title, item.clientName, item.location, item.requirement, customerName(item.customerId)].join(" ").toLowerCase().includes(query.toLowerCase())), [records, status, query, customerName]);
  const open = async (id: string) => { const response = await adminFetch(`/api/admin/projects/${id}`); const data = await response.json() as { project?: ProjectRecord; linked?: ProjectDetail["linked"]; message?: string }; if (!response.ok || !data.project || !data.linked) { setMessage(data.message || "Could not open this project."); return; } setSelected({ project: data.project, linked: data.linked }); };
  const closeCompose = () => { setCompose(false); if (pathname.endsWith("/new")) router.replace("/admin/projects"); };
  const create = async (draft: ProjectDraft) => { const response = await adminFetch("/api/admin/projects", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft) }); const data = await response.json() as { project?: ProjectRecord; message?: string }; if (!response.ok || !data.project) { setMessage(data.message || "Could not create the project."); return false; } setRecords((current) => [data.project!, ...current]); setMessage("Project created."); closeCompose(); return true; };
  const update = async (patch: Partial<ProjectDraft>) => { if (!selected) return false; const response = await adminFetch(`/api/admin/projects/${selected.project.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(patch) }); const data = await response.json() as { project?: ProjectRecord; message?: string }; if (!response.ok || !data.project) { setMessage(data.message || "Could not update the project."); return false; } setSelected((current) => current ? { ...current, project: data.project! } : current); setRecords((current) => current.map((item) => item.id === data.project!.id ? data.project! : item)); setMessage("Project updated."); return true; };
  return <div className="admin-records"><section className="admin-records-toolbar"><div className="admin-records-search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search project, customer, location or requirement" /></div><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option>{statuses.map((item) => <option key={item} value={item}>{item.replaceAll("_", " ")}</option>)}</select><button type="button" onClick={() => setCompose(true)}><Plus size={14} />Add project</button><button type="button" onClick={() => { setLoading(true); void load(); }}>Refresh</button></section>{message && <p className="admin-records-message" role="status">{message}</p>}<div className="admin-records-table-wrap"><div className="admin-records-table admin-projects-table"><div className="admin-records-heading"><span>Created</span><span>Project</span><span>Customer</span><span>Location</span><span>Requirement</span><span>Status</span><span>Expected delivery</span><span /></div>{loading ? <div className="admin-records-empty">Loading projects...</div> : filtered.length ? filtered.map((project) => <button type="button" className="admin-records-row" key={project.id} onClick={() => void open(project.id)}><span>{new Date(project.createdAt).toLocaleDateString("en-IN")}</span><span><strong>{project.title}</strong><small>{project.clientName || project.slug}</small></span><span>{customerName(project.customerId)}</span><span>{project.location || "-"}</span><span><strong>{project.requirement || "Requirement not captured"}</strong><small>{project.scope || "Scope to be confirmed"}</small></span><span><em className={`admin-status ${project.projectStatus}`}>{project.projectStatus.replaceAll("_", " ")}</em></span><span>{project.expectedDeliveryDate ? new Date(`${project.expectedDeliveryDate}T00:00:00`).toLocaleDateString("en-IN") : "-"}</span><ArrowRight size={16} /></button>) : <div className="admin-records-empty"><BriefcaseBusiness size={25} /><strong>No matching projects</strong><p>Create projects to connect customer requirements and quotation history.</p></div>}</div></div>{compose && <ProjectForm title="Add project" customers={customers} onClose={closeCompose} onSubmit={create} />}{selected && <ProjectDrawer detail={selected} customerName={customerName(selected.project.customerId)} customers={customers} onClose={() => setSelected(null)} onUpdate={update} />}</div>;
}

function ProjectForm({ title, initial, customers, onClose, onSubmit }: { title: string; initial?: ProjectRecord; customers: CustomerRecord[]; onClose: () => void; onSubmit: (draft: ProjectDraft) => Promise<boolean> }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const draft: ProjectDraft = { title: String(form.get("title") || ""), customerId: String(form.get("customerId") || ""), clientName: String(form.get("clientName") || ""), location: String(form.get("location") || ""), requirement: String(form.get("requirement") || ""), solution: String(form.get("solution") || ""), scope: String(form.get("scope") || ""), internalNotes: String(form.get("internalNotes") || ""), projectStatus: String(form.get("projectStatus") || "active") as ProjectStatus, startDate: String(form.get("startDate") || ""), expectedDeliveryDate: String(form.get("expectedDeliveryDate") || "") }; setBusy(true); setError(""); const saved = await onSubmit(draft); if (!saved) setError("Check the project details and try again."); setBusy(false); };
  return <div className="admin-drawer-backdrop" role="presentation" onMouseDown={onClose}><aside className="admin-enquiry-drawer admin-customer-form" role="dialog" aria-modal="true" aria-label={title} onMouseDown={(event) => event.stopPropagation()}><header><div><p>PROJECT MASTER</p><h2>{title}</h2><span>Keep scope, delivery timing and commercial records together.</span></div><button type="button" onClick={onClose} aria-label="Close project form"><X size={18} /></button></header><form className="admin-drawer-body admin-customer-fields" onSubmit={submit}><div className="admin-customer-fields-grid"><label>Project name<input name="title" required defaultValue={initial?.title} /></label><label>Customer<select name="customerId" defaultValue={initial?.customerId || ""}><option value="">Not linked yet</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.company || customer.fullName}</option>)}</select></label><label>Client name<input name="clientName" defaultValue={initial?.clientName} /></label><label>Location<input name="location" defaultValue={initial?.location} /></label><label>Project status<select name="projectStatus" defaultValue={initial?.projectStatus || "active"}>{statuses.map((item) => <option key={item} value={item}>{item.replaceAll("_", " ")}</option>)}</select></label><label>Start date<input name="startDate" type="date" defaultValue={initial?.startDate} /></label><label>Expected delivery<input name="expectedDeliveryDate" type="date" defaultValue={initial?.expectedDeliveryDate} /></label></div><label>Requirement<textarea name="requirement" defaultValue={initial?.requirement} /></label><label>Solution / recommendation<textarea name="solution" defaultValue={initial?.solution} /></label><label>Scope<textarea name="scope" defaultValue={initial?.scope} /></label><label>Internal notes<textarea name="internalNotes" defaultValue={initial?.internalNotes} /></label>{error && <p className="admin-form-error">{error}</p>}<div className="admin-customer-form-actions"><button type="button" className="admin-drawer-secondary" onClick={onClose}>Cancel</button><button className="admin-os-primary" disabled={busy}>{busy ? "Saving..." : "Save project"}<ArrowRight size={15} /></button></div></form></aside></div>;
}

function ProjectDrawer({ detail, customerName, customers, onClose, onUpdate }: { detail: ProjectDetail; customerName: string; customers: CustomerRecord[]; onClose: () => void; onUpdate: (patch: Partial<ProjectDraft>) => Promise<boolean> }) { const [editing, setEditing] = useState(false); const { project, linked } = detail; return <div className="admin-drawer-backdrop" role="presentation" onMouseDown={onClose}><aside className="admin-enquiry-drawer" role="dialog" aria-modal="true" aria-label={project.title} onMouseDown={(event) => event.stopPropagation()}><header><div><p>PROJECT RECORD</p><h2>{project.title}</h2><span>{customerName}</span></div><button type="button" onClick={onClose} aria-label="Close project"><X size={18} /></button></header><div className="admin-drawer-body"><section className="admin-drawer-summary"><span><MapPin size={15} />{project.location || "Location not provided"}</span><span><CalendarDays size={15} />Expected delivery: {project.expectedDeliveryDate || "Not set"}</span></section><section className="admin-customer-linked"><div><strong>{linked.enquiries}</strong><span>Enquiries</span></div><div><strong>{linked.quotations}</strong><span>Quotations</span></div></section><section><h3>Requirement and scope</h3><dl><div><dt>Status</dt><dd><em className={`admin-status ${project.projectStatus}`}>{project.projectStatus.replaceAll("_", " ")}</em></dd></div><div><dt>Client</dt><dd>{project.clientName || "Not provided"}</dd></div><div><dt>Started</dt><dd>{project.startDate || "Not set"}</dd></div></dl>{project.requirement && <p className="admin-drawer-message">{project.requirement}</p>}{project.solution && <p className="admin-drawer-message">Recommended: {project.solution}</p>}</section><section className="admin-drawer-controls"><h3>Project control</h3><label>Status<select value={project.projectStatus} onChange={(event) => void onUpdate({ projectStatus: event.target.value as ProjectStatus })}>{statuses.map((item) => <option key={item} value={item}>{item.replaceAll("_", " ")}</option>)}</select></label><button type="button" className="admin-customer-edit" onClick={() => setEditing(true)}><Edit3 size={15} />Edit project details</button></section></div><footer><button type="button" className="admin-drawer-secondary" onClick={onClose}>Close</button><button type="button" className="admin-os-primary" onClick={() => setEditing(true)}><BriefcaseBusiness size={16} />Manage project</button></footer>{editing && <ProjectForm title="Edit project" initial={project} customers={customers} onClose={() => setEditing(false)} onSubmit={async (draft) => { const updated = await onUpdate(draft); if (updated) setEditing(false); return updated; }} />}</aside></div>; }
