"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Archive, ArrowRight, BookOpen, ExternalLink, Eye, PencilLine, Plus, Search, Trash2, X } from "lucide-react";
import { adminFetch } from "@/lib/auth/admin-client";
import AdminRecordPreview from "@/components/admin-record-preview";
import type { DocumentRecord, DocumentStatus, DocumentType, DocumentVisibility, ProductMasterRecord } from "@/lib/db/types";

type Draft = Omit<DocumentRecord, "id" | "createdAt">;
const typeLabels: Record<DocumentType, string> = { brochure: "Brochure", datasheet: "Datasheet", test_certificate: "Test certificate", installation_guide: "Installation guide", other: "Other" };

export default function AdminDocumentsPanel() {
  const [records, setRecords] = useState<DocumentRecord[]>([]); const [products, setProducts] = useState<ProductMasterRecord[]>([]); const [query, setQuery] = useState(""); const [compose, setCompose] = useState(false); const [selected, setSelected] = useState<DocumentRecord | null>(null); const [viewing, setViewing] = useState<DocumentRecord | null>(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  const load = useCallback(async () => { const [documentResponse, productResponse] = await Promise.all([adminFetch("/api/admin/documents"), adminFetch("/api/admin/products")]); const documents = await documentResponse.json() as { documents?: DocumentRecord[]; message?: string }; const productData = await productResponse.json() as { products?: ProductMasterRecord[] }; setRecords(documents.documents || []); setProducts(productData.products || []); if (!documentResponse.ok) setMessage(documents.message || "Could not load documents."); setLoading(false); }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const productName = useCallback((id?: string) => id ? products.find((item) => item.id === id || item.slug === id)?.name || id : "General document", [products]);
  const filtered = useMemo(() => records.filter((item) => [item.title, item.documentType, productName(item.productId), item.materialFamily, item.version, item.visibility, item.status].join(" ").toLowerCase().includes(query.toLowerCase())), [records, query, productName]);
  const save = async (draft: Draft, id?: string) => { const response = await adminFetch(id ? `/api/admin/documents/${id}` : "/api/admin/documents", { method: id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft) }); const data = await response.json() as { document?: DocumentRecord; message?: string }; if (!response.ok || !data.document) { setMessage(data.message || "Could not save the document."); return false; } setRecords((current) => id ? current.map((item) => item.id === id ? data.document! : item) : [data.document!, ...current]); setSelected(null); setCompose(false); setMessage(id ? "Document updated." : "Document record created."); return true; };
  const archive = async (record: DocumentRecord) => { await save({ ...record, status: "archived" }, record.id); };
  const remove = async (record: DocumentRecord) => { const response = await adminFetch(`/api/admin/documents/${record.id}`, { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ record: record.title }) }); const data = await response.json() as { message?: string }; if (!response.ok) { setMessage(data.message || "Could not delete the document."); return; } setRecords((current) => current.filter((item) => item.id !== record.id)); setMessage("Archived document permanently deleted."); };
  return <div className="admin-records"><section className="admin-records-toolbar"><div className="admin-records-search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search title, product, material, type or version" /></div><button type="button" onClick={() => setCompose(true)}><Plus size={14} />Register document</button><button type="button" onClick={() => { setLoading(true); void load(); }}>Refresh</button></section>{message && <p className="admin-records-message">{message}</p>}<div className="admin-records-table-wrap"><div className="admin-records-table admin-documents-table"><div className="admin-records-heading"><span>Document</span><span>Product / material</span><span>Version / date</span><span>Visibility</span><span>Status</span><span>File</span><span>Actions</span></div>{loading ? <div className="admin-records-empty">Loading documents...</div> : filtered.length ? filtered.map((record) => <div className="admin-records-row" key={record.id}><span><strong>{record.title}</strong><small>{typeLabels[record.documentType]}</small></span><span><strong>{productName(record.productId)}</strong><small>{record.materialFamily || "Material not set"}</small></span><span><strong>{record.version || "No version"}</strong><small>{record.documentDate || "Date not set"}</small></span><span>{record.visibility === "public" ? "Public" : "Internal"}</span><span><em className={`admin-status ${record.status === "current" ? "active" : "archived"}`}>{record.status}</em></span><a className="admin-document-link" href={record.fileUrl} target="_blank" rel="noreferrer"><ExternalLink size={15} />Open file</a><span className="admin-variant-actions"><button type="button" className="admin-variant-toggle" onClick={() => setViewing(record)}><Eye size={15} />View</button><button type="button" className="admin-variant-toggle" onClick={() => setSelected(record)}><PencilLine size={15} />Edit</button>{record.status === "current" ? <button type="button" className="admin-variant-toggle" onClick={() => void archive(record)}><Archive size={15} />Archive</button> : <button type="button" className="admin-variant-toggle admin-variant-delete" onClick={() => void remove(record)}><Trash2 size={15} />Delete</button>}</span></div>) : <div className="admin-records-empty"><BookOpen size={25} /><strong>No matching documents</strong><p>Register public brochures and protected technical documents here.</p></div>}</div></div>{compose && <DocumentForm title="Register document" products={products} onClose={() => setCompose(false)} onSubmit={(draft) => save(draft)} />}{selected && <DocumentForm title="Edit document" initial={selected} products={products} onClose={() => setSelected(null)} onSubmit={(draft) => save(draft, selected.id)} />}{viewing && <AdminRecordPreview title={viewing.title} record={viewing as unknown as Record<string, unknown>} onClose={() => setViewing(null)} />}</div>;
}

function DocumentForm({ title, initial, products, onClose, onSubmit }: { title: string; initial?: DocumentRecord; products: ProductMasterRecord[]; onClose: () => void; onSubmit: (draft: Draft) => Promise<boolean> }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const draft: Draft = { title: String(form.get("title") || ""), documentType: String(form.get("documentType") || "other") as DocumentType, productId: String(form.get("productId") || ""), materialFamily: String(form.get("materialFamily") || ""), version: String(form.get("version") || ""), documentDate: String(form.get("documentDate") || ""), fileUrl: String(form.get("fileUrl") || ""), visibility: String(form.get("visibility") || "internal") as DocumentVisibility, status: String(form.get("status") || "current") as DocumentStatus, replacedById: String(form.get("replacedById") || "") }; setBusy(true); setError(""); const saved = await onSubmit(draft); if (!saved) setError("Check the document details and URL."); setBusy(false); };
  return <div className="admin-drawer-backdrop" onMouseDown={onClose}><aside className="admin-enquiry-drawer admin-customer-form" onMouseDown={(event) => event.stopPropagation()}><header><div><p>DOCUMENT CONTROL</p><h2>{title}</h2><span>Archive a superseded file and link its replacement instead of overwriting history.</span></div><button type="button" onClick={onClose}><X size={18} /></button></header><form className="admin-drawer-body admin-customer-fields" onSubmit={submit}><div className="admin-customer-fields-grid"><label>Title<input name="title" required defaultValue={initial?.title} /></label><label>Document type<select name="documentType" defaultValue={initial?.documentType || "brochure"}>{Object.entries(typeLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>Linked product<select name="productId" defaultValue={initial?.productId || ""}><option value="">General / not product-specific</option>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label>Material family<input name="materialFamily" defaultValue={initial?.materialFamily} /></label><label>Version<input name="version" defaultValue={initial?.version} placeholder="1.0" /></label><label>Document date<input name="documentDate" type="date" defaultValue={initial?.documentDate} /></label><label>Visibility<select name="visibility" defaultValue={initial?.visibility || "internal"}><option value="public">Public</option><option value="internal">Internal only</option></select></label><label>Status<select name="status" defaultValue={initial?.status || "current"}><option value="current">Current</option><option value="archived">Archived</option></select></label></div><label>File URL or relative path<input name="fileUrl" required defaultValue={initial?.fileUrl} placeholder="/brochures/xlpe-sheet-insulation or https://..." /></label><label>Replacement document ID (optional)<input name="replacedById" defaultValue={initial?.replacedById} /></label>{error && <p className="admin-form-error">{error}</p>}<div className="admin-customer-form-actions"><button type="button" className="admin-drawer-secondary" onClick={onClose}>Cancel</button><button className="admin-os-primary" disabled={busy}>{busy ? "Saving..." : "Save document"}<ArrowRight size={15} /></button></div></form></aside></div>;
}
