export type CatalogueProduct = {
  slug: string;
  name: string;
  category: string;
  categorySlug: string;
  family: string;
  image: string;
  shortDescription: string;
  overview: string;
  idealFor: string[];
  keyBenefits: string[];
  availableForms: string[];
  selectionNotes: string[];
  brochureCompany: string;
  technicalData?: { description: string; standard: string; unit: string; value: string; isSection?: boolean }[];
  technicalDataNote?: string;
};

const images = {
  rubber: "/assets/products/nitrile-rubber-studio.png",
  nitrileSheetTube: "/assets/products/nitrile-sheet-and-tubes.png",
  nitrileAcoustic: "/assets/products/nitrile-acoustic-foam.jpeg",
  glass: "/assets/products/glass-wool-studio.png",
  rock: "/assets/products/rock-wool-studio.png",
  xlpe: "/assets/products/xlpe-studio.png",
  xlpeSheet: "/assets/products/xlpe-sheet.png",
  xlpeTube: "/assets/products/xlpe-tubing.jpeg",
  xlpeUnderdeck: "/assets/products/xlpe-underdeck.jpeg",
  glassWoolBlanket: "/assets/products/glass-wool-blanket.png",
  glassWoolDuctBoard: "/assets/products/glass-wool-duct-board.png",
  glassWoolFlexibleDuct: "/assets/products/glass-wool-flexible-duct.png",
  glassWoolAcousticBoard: "/assets/products/glass-wool-acoustic-board.png",
  glassWoolPipe: "/assets/products/glass-wool-pipe-insulation.png",
  rockWoolSlab: "/assets/products/rock-wool-slab.png",
  rockWoolPipe: "/assets/products/rock-wool-pipe-section.png",
  rockWoolAcoustic: "/assets/products/rock-wool-acoustic-panel.png",
  ceramicFibre: "/assets/products/ceramic-fibre-blanket.png",
  xpsBoard: "/assets/products/xps-insulation-board.png",
  pirPurPanel: "/assets/products/pir-pur-insulation-panel.png",
  epsBoard: "/assets/products/eps-insulation-board.png",
  foilBubble: "/assets/products/foil-bubble-insulation.png",
  epeFoilFoam: "/assets/products/epe-foil-foam-insulation.png",
  metalCladding: "/assets/products/metal-insulation-cladding.png",
  aerogel: "/assets/products/aerogel-insulation-blanket.png",
  massLoadedVinyl: "/assets/products/mass-loaded-vinyl-barrier.png",
  polyesterAcoustic: "/assets/products/polyester-acoustic-panel.png",
  thermalJacket: "/assets/products/thermal-insulation-jacket.png",
  waterTankCover: "/assets/products/water-tank-cover.png",
  adhesive: "/assets/products/insulation-adhesive.png",
  tapes: "/assets/products/insulation-tapes.png",
  boards: "/assets/products/rigid-boards-studio.png",
  roof: "/assets/products/roofing-peb-studio.png",
} as const;

export const catalogue: CatalogueProduct[] = [
  {
    slug: "insulation-adhesive", name: "Insulation Adhesive", category: "HVAC / Cold Insulation", categorySlug: "hvac-insulation", family: "Insulation accessories", image: images.adhesive,
    shortDescription: "Compatible insulation adhesive for bonding selected insulation materials, joints and installation details.",
    overview: "Insulation adhesive is a supporting installation component selected to bond compatible insulation to the prepared substrate or adjoining insulation material. It helps create a secure, continuous build-up when used with the specified insulation core, facing and installation method. Surface condition, coverage, application sequence and any drying or curing requirement must follow the selected adhesive literature.",
    idealFor: ["HVAC ducts, equipment and broad insulation surfaces", "Insulation joints and local detail work where the specified system requires adhesive bonding", "Thermal and acoustic insulation assemblies requiring a compatible installation adhesive"],
    keyBenefits: ["Supports controlled bonding within a compatible insulation system", "Helps maintain neat installation around joints, fittings and local transitions", "Can be selected around the insulation core, facing and substrate", "Supports practical project installation when applied to approved instructions"],
    availableForms: ["Insulation adhesive in the selected pack size", "Application with the specified tool and substrate preparation", "Compatible options selected around insulation core and facing", "Project-specific adhesive coverage and application sequence"],
    selectionNotes: ["Confirm adhesive compatibility with the insulation material, facing and substrate", "Follow the supplied adhesive literature for preparation, coverage, working time and any drying or curing requirement", "Confirm ventilation, safety and handling requirements for the selected product", "Use the approved project installation method for final acceptance"], brochureCompany: "RAC Insutech",
    technicalData: [
      { description: "Material family", standard: "Selected adhesive literature", unit: "", value: "Insulation installation adhesive" },
      { description: "Primary use", standard: "Project installation method", unit: "", value: "Bonding compatible insulation to substrate, joints and local details" },
      { description: "Compatibility", standard: "Selected adhesive literature", unit: "", value: "Confirm against insulation core, facing, substrate and service condition" },
      { description: "Application requirements", standard: "Selected adhesive literature", unit: "", value: "Confirm surface preparation, coverage, working time and any drying or curing requirement" },
      { description: "Handling and safety", standard: "Selected adhesive literature", unit: "", value: "Follow the product safety, ventilation and storage instructions" },
    ],
    technicalDataNote: "This RAC product brief references the supplied adhesive literature for early-stage selection. Confirm the exact product grade, coverage, application method, temperature limits and approved installation instructions from the selected adhesive document before ordering or installation.",
  },
  {
    slug: "insulation-tapes", name: "Insulation Tapes", category: "HVAC / Cold Insulation", categorySlug: "hvac-insulation", family: "Insulation accessories", image: images.tapes,
    shortDescription: "Insulation tape options for joints, laps, facing seams, repairs and system-led finishing details.",
    overview: "Insulation tapes are installation accessories used to treat joints, laps, seams and minor repair details in compatible insulation assemblies. The chosen tape should match the insulation core, facing, service condition and the required joint function—such as facing continuity, vapour-control detailing, protection or mechanical reinforcement. Final tape backing, width and adhesive system must follow the selected tape literature.",
    idealFor: ["Facing seams and laps on HVAC and cold-service insulation", "Duct, pipe, equipment and roof insulation joint detailing", "Repairs and finishing details within compatible thermal or acoustic insulation assemblies"],
    keyBenefits: ["Helps make insulation seams and laps more continuous", "Supports neat, practical finishing at local joints and transitions", "Allows the tape backing and width to be selected for the detail", "Complements the specified insulation-facing and joint-treatment method"],
    availableForms: ["Insulation tape rolls in the selected backing and width", "Tape formats for facing seams, laps, repair and protective detailing", "Compatible adhesive systems selected around service and substrate", "Project-specific joint-treatment combinations"],
    selectionNotes: ["Confirm tape compatibility with the insulation core, facing and intended joint function", "Select backing, width and adhesive system from the supplied tape literature", "Prepare and dry the application surface as required by the selected tape instructions", "Confirm the final detail against the approved insulation installation method"], brochureCompany: "RAC Insutech",
    technicalData: [
      { description: "Material family", standard: "Selected tape literature", unit: "", value: "Insulation joint and facing tape" },
      { description: "Primary use", standard: "Project installation method", unit: "", value: "Joints, laps, facing seams, repairs and local finishing details" },
      { description: "Tape selection", standard: "Selected tape literature", unit: "", value: "Confirm backing, width and adhesive system for the intended detail" },
      { description: "Compatibility", standard: "Selected tape literature", unit: "", value: "Confirm against insulation core, facing, substrate and service condition" },
      { description: "Application requirements", standard: "Selected tape literature", unit: "", value: "Confirm surface preparation, overlap and pressure/application method" },
    ],
    technicalDataNote: "This RAC product brief references the supplied insulation-tape literature for early-stage selection. Confirm the exact tape configuration, adhesive system, dimensions, temperature limits and approved installation instructions from the selected tape document before ordering or installation.",
  },
  {
    slug: "nitrile-rubber-tube", name: "Nitrile Rubber Tube", category: "Cold insulation", categorySlug: "cold-insulation", family: "Elastomeric foam", image: images.nitrileSheetTube,
    shortDescription: "Fire-retardant, closed-cell elastomeric nitrile tubing for pipe insulation and condensation control.",
    overview: "Nitrile rubber tube insulation is a flexible, pre-formed, closed-cell elastomeric foam for pipework. It is suited to installations that need moisture-conscious thermal insulation with fast fitting around HVAC, plumbing, refrigeration and process service lines.",
    idealFor: ["HVAC, split and window A/C piping", "Plumbing, drainage and solar piping", "Cold storage, clean rooms and process pipework"], keyBenefits: ["High water-vapour resistance for low-temperature systems", "Lightweight, flexible and fibre-free tubing", "Closed-cell structure with stable thermal conductivity", "Resistant to fungi, ozone and mild chemical exposure"], availableForms: ["Pre-formed tube lengths: 1830 mm", "Thicknesses from 6 mm to 19 mm", "Pipe internal diameters from 6 mm to 42 mm", "Tube combinations in common copper, MS, PVC and PPR pipe sizes"], selectionNotes: ["Match the tube internal diameter and thickness to the pipe and service", "Confirm the operating condition and specified fire-performance requirement", "Use the approved technical submittal for the offered material"], brochureCompany: "RAC Insutech",
    technicalData: [
      { description: "Cellular structure", standard: "Visual", unit: "", value: "Very fine, closed cell" },
      { description: "Density", standard: "ASTM D 1667", unit: "kg/m3", value: "60 - 80" },
      { description: "Thermal conductivity at mean temperature 25 deg C", standard: "EN 12667:2001", unit: "W/m.K", value: "0.034" },
      { description: "Temperature limits", standard: "", unit: "deg C", value: "-55 to +105" },
      { description: "Thermal stability (9 days at 90 deg C)", standard: "ASTM C534 / C534M-11", unit: "%", value: "3.3" },
      { description: "Fire resistance", standard: "UL 94", unit: "", value: "V-0 approved" },
      { description: "Toxicity index", standard: "NES 713", unit: "", value: "2.59" },
      { description: "Water absorption", standard: "ASTM D 1056", unit: "% W/W", value: "<2.00%" },
      { description: "Water-vapour permeability", standard: "ASTM E 96", unit: "g/Pa.m.hr", value: "2.25 x 10-7" },
      { description: "Mildew resistance", standard: "ASTM G 21", unit: "", value: "No fungal growth" },
      { description: "Weather and UV resistance", standard: "", unit: "", value: "Good" },
      { description: "Ozone resistance", standard: "ASTM D 1149", unit: "", value: "Excellent" },
      { description: "Flexibility", standard: "IS 12657-1989", unit: "", value: "Excellent" },
      { description: "Corrosion", standard: "", unit: "", value: "Negligible" },
      { description: "Chemical resistance", standard: "ASTM D 543", unit: "", value: "No effect of mild acids and alkali" },
    ],
    technicalDataNote: "Reference values are supplied for early-stage selection only. Confirm exact dimensions, product configuration and approved technical data before ordering.",
  },
  {
    slug: "nitrile-rubber-sheet", name: "Nitrile Rubber Sheet", category: "Cold insulation", categorySlug: "cold-insulation", family: "Elastomeric foam", image: images.nitrileSheetTube,
    shortDescription: "High-performance, flexible closed-cell nitrile sheet for ducts, equipment and condensation-control insulation.",
    overview: "Nitrile rubber sheet is a flexible, closed-cell elastomeric foam designed to control condensation and limit heat gain or loss. Its sheet format is suited to HVAC ductwork, equipment, tanks, fittings and other broad or irregular surfaces where pre-formed tubing is not the right geometry.",
    idealFor: ["HVAC insulation, refrigeration and chilled-water systems", "A/C ductwork, tanks and pipe fittings", "Clean rooms, cold storage and underdeck insulation"], keyBenefits: ["Low thermal conductivity and closed-cell moisture resistance", "Fibre-free, low-VOC material", "Resists fungi and bacterial growth", "Flexible sheets with optional protective laminations"], availableForms: ["Flexible sheet insulation", "Reinforced aluminium foil, glass cloth and other laminated formats", "Plain and faced material for indoor or protected external use"], selectionNotes: ["Confirm the sheet thickness, facing and joint detail", "Review the service temperature and moisture-control requirement", "Use the approved technical submittal for the final supplied material"], brochureCompany: "RAC Insutech",
    technicalData: [
      { description: "Density", standard: "ASTM D 1622", unit: "kg/m3", value: "50 +/- 5" },
      { description: "Temperature range*", standard: "EN 14706 and EN 14304", unit: "deg C", value: "0 to 105; -1 to -50 subject to the stated application note" },
      { description: "Thermal conductivity", standard: "EN 12667 / ISO 8497", unit: "", value: "", isSection: true },
      { description: "K value at 0 deg C", standard: "EN 12667 / ISO 8497", unit: "W/m.K", value: "0.035" },
      { description: "K value at +20 deg C", standard: "EN 12667 / ISO 8497", unit: "W/m.K", value: "0.036" },
      { description: "K value at +40 deg C", standard: "EN 12667 / ISO 8497", unit: "W/m.K", value: "0.038" },
      { description: "Water-vapour diffusion resistance", standard: "EN 12806:2013", unit: "", value: "10,000" },
      { description: "Fire performance index (I)", standard: "BS 476 Part 6", unit: "", value: "12" },
      { description: "Fire propagation index (O) and sub-index (i1)", standard: "BS 476 Part 6", unit: "", value: "O; 6" },
      { description: "Surface spread of flame", standard: "BS 476 Part 7", unit: "", value: "Class 1; final flame spread 165 mm (25)" },
      { description: "Reaction to fire", standard: "UL 94 HBF-1", unit: "", value: "Passed self-extinguishing in 30 sec" },
      { description: "Reaction to fire", standard: "UL 94 HB V0", unit: "", value: "Passed self-extinguishing in 10 sec as alternate time for each specimen" },
      { description: "Antimicrobial activity", standard: "ISO 846:1997", unit: "", value: "No growth appearance for 28 days" },
      { description: "Resistance to fungi", standard: "C1338-00", unit: "", value: "Zero fungi" },
      { description: "CFC, HCFC and related compounds", standard: "STD wet chemistry", unit: "Compliance", value: "Not detected (tested for 25 parameters)" },
      { description: "RoHS", standard: "ELV 6 full for compounds", unit: "Compliance", value: "Passed" },
      { description: "Environment friendly", standard: "GBC/CII Ver: 1.0", unit: "Compliance", value: "Green product" },
    ],
    technicalDataNote: "*The supplied literature includes a service-temperature application note for glued sheet. Final performance and approval must be confirmed against the exact material and project conditions.",
  },
  {
    slug: "nitrile-acoustic-foam", name: "Nitrile Acoustic Foam", category: "Acoustic insulation", categorySlug: "acoustic-insulation", family: "Elastomeric foam", image: images.nitrileAcoustic,
    shortDescription: "Flexible, open-cell elastomeric acoustic foam for sound absorption, barrier and vibration-damping applications.",
    overview: "Nitrile acoustic foam is a flexible, open-cell elastomeric product for acoustic treatment. Its pore geometry supports sound absorption, while its density contributes sound-barrier and vibration-damping characteristics in HVAC, industrial and interior acoustic assemblies.",
    idealFor: ["HVAC duct and AHU lining", "Plant rooms, pump rooms and genset canopies", "Commercial, marine, home-theatre and room-acoustic treatment"], keyBenefits: ["Sound absorption with documented NRC values by thickness", "Flexible, resilient and easy to cut or fabricate", "Dust- and fibre-free, moisture- and chemical-resistant", "Fire-retardant, CFC/HCFC-free material"], availableForms: ["1 m x 1 m panels", "10 mm, 15 mm, 20 mm and 25 mm thicknesses", "Other thicknesses on request", "Can be perforated, die-punched, laminated or embossed"], selectionNotes: ["Select thickness against the required acoustic absorption and transmission-loss objective", "Confirm the complete assembly, lining method and fire requirement", "Use the approved technical submittal for the offered material"], brochureCompany: "RAC Insutech",
    technicalData: [
      { description: "Maximum service temperature", standard: "", unit: "deg C", value: "+85" },
      { description: "Minimum service temperature", standard: "", unit: "deg C", value: "-20" },
      { description: "Thermal conductivity", standard: "ASTM C 518", unit: "W/m.K", value: "0.05868" },
      { description: "Fire performance", standard: "UL 94", unit: "", value: "HF 1" },
      { description: "Density", standard: "ASTM D 3575", unit: "kg/m3", value: ">=30" },
      { description: "Tensile strength at break", standard: "", unit: "kg/cm2", value: "1.5" },
      { description: "Elongation at break", standard: "", unit: "%", value: "210" },
      { description: "Tear strength", standard: "", unit: "kg/cm", value: "7.0" },
      { description: "Water absorption", standard: "", unit: "%", value: "2%" },
      { description: "Sound transmission loss", standard: "ASTM E 2611", unit: "dB", value: "11" },
      { description: "Surface spread of flame", standard: "BS 476 Part 7", unit: "", value: "Class 1" },
      { description: "Acoustic performance by thickness", standard: "ASTM C 423 / ISO 354", unit: "", value: "", isSection: true },
      { description: "Noise reduction coefficient (NRC), 10 mm", standard: "ASTM C 423 / ISO 354", unit: "", value: "0.35" },
      { description: "Noise reduction coefficient (NRC), 15 mm", standard: "ASTM C 423 / ISO 354", unit: "", value: "0.48" },
      { description: "Noise reduction coefficient (NRC), 20 mm", standard: "ASTM C 423 / ISO 354", unit: "", value: "0.53" },
      { description: "Noise reduction coefficient (NRC), 25 mm", standard: "ASTM C 423 / ISO 354", unit: "", value: "0.60" },
      { description: "Weighted sound absorption coefficient (alpha w), 10 / 15 / 20 / 25 mm", standard: "EN ISO 11654", unit: "", value: "0.20 / 0.30 / 0.40 / 0.35" },
      { description: "Acoustic class, 10 / 15 / 20 / 25 mm", standard: "EN ISO 11654", unit: "", value: "E / D / D / D" },
    ],
    technicalDataNote: "Acoustic values are reference values from the supplied literature. Final acoustic performance depends on thickness, installation, surrounding construction and project conditions.",
  },
  {
    slug: "xlpe-tube-insulation", name: "XLPE Tube Insulation", category: "HVAC insulation", categorySlug: "hvac-insulation", family: "Cross-linked polyethylene", image: images.xlpeTube,
    shortDescription: "Fire-retardant, closed-cell XLPE tubing for HVAC, chiller, plumbing and industrial pipe insulation.",
    overview: "XLPE tube insulation is a non-fibrous, chemically cross-linked polyethylene foam supplied as pre-formed tubing. Its closed-cell construction is intended for thermal insulation of chiller, HVAC, hot- and cold-water, plumbing and drain-pipe systems, with suitable facings available for specific exposure conditions.",
    idealFor: ["Chiller piping in pharmaceutical and industrial facilities", "Solar, cold-storage and clean-room piping", "Split A/C, HVAC, plumbing and drain-pipe insulation"], keyBenefits: ["More than 85% closed-cell structure", "Low, stable K value and moisture resistance", "Pre-slit tubing options for straightforward installation", "Non-fibrous material with optional UV-resistant facings"], availableForms: ["Pre-formed tubing with and without installation flap", "Tube profiles in various dimensions, with IDs up to 450 mm", "Metallised PET, aluminium foil and UV-barrier facings", "XLPE composite with EPE tube available"], selectionNotes: ["Select the tube ID around the actual pipe specification", "Confirm thickness, facing and operating temperature", "Use the approved technical submittal for the exact offered product"], brochureCompany: "RAC Insutech",
    technicalData: [
      { description: "Thermal stability at 90 deg C / 24 hrs", standard: "ASTM D 3575", unit: "%", value: "5%" },
      { description: "Density range", standard: "ASTM D 3575", unit: "kg/m3", value: "28 +/- 3" },
      { description: "Thermal conductivity (K value) at 23 deg C", standard: "ASTM C 518", unit: "W/m.K", value: "0.0328 - 0.0355" },
      { description: "Water absorption", standard: "ASTM D 1056", unit: "%", value: "2%" },
      { description: "Water-vapour transmission, foil side", standard: "ASTM E 96", unit: "g/m2/24 hrs for 7 days", value: "0.041" },
      { description: "Resistance to chemicals", standard: "ASTM D 543", unit: "Compliance", value: "Complied" },
      { description: "Volume percentage of closed cell", standard: "Visual at 10X magnification", unit: "%", value: "85" },
      { description: "Water-vapour resistance factor, foil side", standard: "EN 12086", unit: "", value: "11,000" },
      { description: "Fire characteristics", standard: "", unit: "", value: "", isSection: true },
      { description: "Surface spread of flame (plain and foil-faced material)", standard: "BS 476 Part 7, Class 1", unit: "Compliance", value: "Complied" },
      { description: "Fire propagation (aluminium-foil-faced material only)", standard: "BS 476 Part 6 & 7, Class 0", unit: "Compliance", value: "Complied" },
      { description: "Fire spread index and smoke density", standard: "ASTM E 84, Class A", unit: "", value: "Index <12.0; smoke density 7.40; complied*" },
      { description: "Operating temperature range (feature reference)", standard: "", unit: "deg C", value: "-40 to 115" },
    ],
    technicalDataNote: "Reference values are supplied for early-stage selection only. Confirm the exact tube profile, density, facing and approved technical documentation before ordering.",
  },
  {
    slug: "xlpe-sheet-insulation", name: "XLPE Sheet Insulation", category: "HVAC insulation", categorySlug: "hvac-insulation", family: "Cross-linked polyethylene", image: images.xlpeSheet,
    shortDescription: "Fire-retardant, closed-cell XLPE sheet for ductwork, equipment and thermal-insulation assemblies.",
    overview: "XLPE sheet insulation is a non-fibrous, chemically cross-linked polyethylene foam for broad duct, equipment and fabricated insulation coverage. Its closed-cell structure supports moisture-conscious thermal assemblies, while sheet and roll formats allow clean cutting, wrapping and joint detailing.",
    idealFor: ["A.C. humidification and duct insulation", "Cold insulation and pipework details", "Equipment, services and custom-cut insulation"], keyBenefits: ["More than 85% closed-cell structure", "Low water and moisture absorption", "Non-fibrous, non-irritant material with no airborne fibres", "Weather-resistant, easy-to-handle sheet format"], availableForms: ["Plain sheet: 3-13 mm thickness and 1250 mm width", "Laminated sheet: above 3 mm thickness and 1220 mm width", "Sheet and roll formats", "Factory-applied metallised PET, aluminium foil, UV barrier or adhesive-backed facings"], selectionNotes: ["Confirm the service temperature, thickness and density required", "Choose the facing around vapour control, exposure and joint treatment", "Verify the final project specification and approved technical submittal before ordering"], brochureCompany: "RAC Insutech",
    technicalData: [
      { description: "Operating temperature (under intermittent exposure)*", standard: "ASTM D 3575", unit: "deg C", value: "-40 to 100; 85 to 115 for shorter exposure time" },
      { description: "Density range", standard: "ASTM D 3575", unit: "kg/m3", value: "25 +/- 3" },
      { description: "Thermal conductivity (K value) (for reference only)*", standard: "", unit: "", value: "", isSection: true },
      { description: "K value at 0 deg C", standard: "ASTM C 518", unit: "W/m.K", value: "0.0318 - 0.0332" },
      { description: "K value at 23 deg C", standard: "ASTM C 518", unit: "W/m.K", value: "0.0328 - 0.0345" },
      { description: "K value at 45 deg C", standard: "ASTM C 518", unit: "W/m.K", value: "0.0333 - 0.0360" },
      { description: "Water absorption*", standard: "ASTM D 1056", unit: "%", value: "2%" },
      { description: "Water vapour transmission rate, foil side*", standard: "ASTM E 96", unit: "g/m2/24 hrs", value: "0.034" },
      { description: "Water vapour permeability*", standard: "EN 12086", unit: "mg/m.Pa.s", value: "< 6 x 10-3" },
      { description: "Water-vapour resistance factor, foam side", standard: "EN 12086", unit: "", value: "8,000" },
      { description: "Water-vapour resistance, foil side", standard: "EN 12086", unit: "", value: ">60,000" },
      { description: "Fire characteristics*", standard: "", unit: "", value: "", isSection: true },
      { description: "Surface spread of flame (plain and foil-faced material)", standard: "BS 476 Part 7, Class 1", unit: "Compliance", value: "Complied" },
      { description: "Fire propagation (aluminium-foil-faced material only)", standard: "BS 476 Part 6 & 7, Class 0", unit: "Compliance", value: "Complied" },
      { description: "UL 94 certification", standard: "UL 94 HBF", unit: "Compliance", value: "Certified" },
      { description: "Fire spread index and smoke developed index", standard: "ASTM E 84, Class A", unit: "Compliance", value: "Complied* (25 FSI and 45 SDI)" },
      { description: "Resistance to chemicals", standard: "ASTM D 543", unit: "Compliance", value: "Complied" },
      { description: "Sound transmission class", standard: "ASTM E 2611", unit: "dB", value: ">25" },
      { description: "RoHS", standard: "RoHS/EU/95/Recast", unit: "Compliance", value: "Complied" },
      { description: "Green product", standard: "GBC/CII version 01 (IGBC)", unit: "Compliance", value: "Complied" },
      { description: "Fire protection on railway vehicles", standard: "EN 45545-2:2013+A1:2015", unit: "Compliance", value: "Complied R1 and HL3" },
    ],
    technicalDataNote: "Reference values are supplied for early-stage selection only. Final performance varies by density, thickness, facing and product format; use the approved technical submittal for the exact material offered.",
  },
  {
    slug: "xlpe-underdeck-insulation", name: "XLPE Underdeck Insulation", category: "Roof & PEB insulation", categorySlug: "roof-peb-insulation", family: "Cross-linked polyethylene", image: images.xlpeUnderdeck,
    shortDescription: "Foil-faced, closed-cell XLPE underdeck insulation for PEB and metal-roof thermal and vapour-control layers.",
    overview: "XLPE underdeck insulation is a closed-cell, cross-linked polyethylene foam used beneath metal roofing in pre-engineered building assemblies. Double aluminium-foil facings can provide a reflective layer and vapour-control component when installed with the required laps, tape and roof-fixing details.",
    idealFor: ["PEB sheds and industrial metal roofs", "Warehouses and manufacturing facilities", "Roof assemblies requiring thermal, reflective and secondary water-barrier layers"], keyBenefits: ["Reflective foil faces help manage radiant energy transfer", "Closed-cell foam supports a compact vapour-control layer", "Can act as a secondary water barrier when installed along the roof slope", "Low-weight roll handling for simultaneous roofing installation"], availableForms: ["Aluminium-foil-faced underdeck rolls", "Foil facing on both sides", "Roll format installed over purlins and beneath metal roofing", "Compatible aluminium foil tape and fixing details for sealed laps"], selectionNotes: ["Confirm the PEB roof build-up, purlin spacing and required thickness", "Install laps, edge details and tape as part of a continuous system", "Verify the final product, density and facing against the approved submittal"], brochureCompany: "RAC Insutech",
    technicalData: [
      { description: "Operating temperature (under intermittent exposure)*", standard: "ASTM D 3575", unit: "deg C", value: "-40 to 85; 85 to 115 for shorter exposure time" },
      { description: "Density", standard: "ASTM D 3575", unit: "kg/m3", value: "28 +/- 3" },
      { description: "Thermal conductivity (K value)*", standard: "ASTM C 518", unit: "", value: "", isSection: true },
      { description: "K value at 0 deg C", standard: "ASTM C 518", unit: "W/m.K", value: "0.0318 - 0.0332" },
      { description: "K value at 23 deg C", standard: "ASTM C 518", unit: "W/m.K", value: "0.0328 - 0.0345" },
      { description: "K value at 45 deg C", standard: "ASTM C 518", unit: "W/m.K", value: "0.0333 - 0.0360" },
      { description: "Solar direct reflectance", standard: "ASTM 1980-11", unit: "", value: "96.3" },
      { description: "Water absorption*", standard: "ASTM D 1056", unit: "%", value: "2%" },
      { description: "Water-vapour resistance factor, foam side", standard: "EN 12086", unit: "", value: "2,800" },
      { description: "Water-vapour resistance factor, foil side", standard: "EN 12086", unit: "", value: ">11,000" },
      { description: "Oxygen index", standard: "ASTM D 2863", unit: "Index", value: "28" },
      { description: "Surface spread of flame (aluminium-foil-faced material)", standard: "BS 476 Part 7, Class 1", unit: "Compliance", value: "Complied" },
      { description: "Fire propagation (aluminium-foil-faced material)", standard: "BS 476 Part 6 & 7, Class 0", unit: "Compliance", value: "Complied" },
      { description: "Sound insulation characteristic with GI sheet", standard: "", unit: "STC", value: "19 - 30 (reference curve)" },
    ],
    technicalDataNote: "*Reference values are supplied for early-stage selection only. Final performance is specific to the offered product density, thickness, facing and roof assembly.",
  },
  {
    slug: "glass-wool-blanket", name: "Glass Wool Blanket", category: "Hot insulation", categorySlug: "hot-insulation", family: "Glass mineral wool", image: images.glassWoolBlanket,
    shortDescription: "Flexible resin-bonded glass-wool blanket for thermal, acoustic and fire-conscious roof, wall, HVAC and industrial assemblies.",
    overview: "Glass wool blanket is a resilient, resin-bonded mineral-fibre roll format for broad thermal and acoustic coverage. The blanket can follow roofs, ceilings, walls and ductwork, while density, thickness, facing and the complete installed assembly are selected around the project’s thermal, fire, moisture and sound-control needs.",
    idealFor: ["Metal roofs, RCC underdecks, masonry walls and drywall", "HVAC duct thermal insulation and acoustic wraps", "Low-temperature equipment, solar-water-heater and mobility applications"], keyBenefits: ["Low reference thermal conductivity at 25 deg C mean temperature", "Reference sound absorption up to NRC 0.95", "Lightweight, flexible roll handling with plain or faced options", "Reference non-combustible material performance"], availableForms: ["Density range: 10 - 48 kg/m3", "Thickness range: 25 - 130 mm", "Width: 1.1 - 1.2 m; length: 7.5 - 30 m", "Plain or faced rolls with aluminium, metallised-polypropylene or tissue-facing options"], selectionNotes: ["Confirm density, thickness and facing against the thermal, acoustic and fire objectives", "Coordinate joint treatment, vapour strategy and the installation method with the complete assembly", "Use the final offered product’s approved technical submittal for project sign-off"], brochureCompany: "RAC Insutech",
    technicalData: [
      { description: "Material range and thermal performance", standard: "", unit: "", value: "", isSection: true },
      { description: "Material composition", standard: "", unit: "", value: "Resin-bonded glass wool" },
      { description: "Reference product range", standard: "", unit: "kg/m3 / mm", value: "Density 10 - 48; thickness 25 - 130" },
      { description: "Reference dimensions", standard: "", unit: "m", value: "Width 1.1 - 1.2; length 7.5 - 30" },
      { description: "Facing options", standard: "", unit: "", value: "Plain; aluminium, metallised-polypropylene or tissue facings" },
      { description: "Reference standard", standard: "IS 8183", unit: "", value: "Applicable code reference" },
      { description: "Thermal conductivity at 25 deg C mean temperature", standard: "IS 8183 / IS 3346", unit: "W/m.K", value: "0.030 - 0.041" },
      { description: "Thermal resistance at specific thickness", standard: "", unit: "m2.K/W", value: "25 mm: 0.6 - 0.8; 50 mm: 1.2 - 1.6" },
      { description: "Noise reduction coefficient", standard: "ASTM C 423 / ISO 354", unit: "NRC", value: "0.65 - 0.95" },
      { description: "Fire, moisture and material properties", standard: "", unit: "", value: "", isSection: true },
      { description: "Non-combustibility", standard: "BS 476 Part 4 / IS 8183 / EN 13501", unit: "", value: "Non-combustible / incombustible; A1 reference classification" },
      { description: "Surface spread of flame", standard: "BS 476 Part 7", unit: "", value: "Nil; Class 1" },
      { description: "Fire propagation", standard: "BS 476 Parts 6 and 7", unit: "", value: "Class 0; index I <12; sub-index i1 <6" },
      { description: "Moisture content", standard: "IS 3144 / IS 8183", unit: "%", value: "<2" },
      { description: "Shot content", standard: "IS 3144 / IS 8183", unit: "", value: "Nil" },
      { description: "Sulphur and chloride", standard: "IS 3144 / IS 8183", unit: "", value: "Negligible" },
      { description: "Mould growth", standard: "IS 3144 / IS 8183", unit: "", value: "None" },
      { description: "Alkalinity", standard: "IS 8183", unit: "pH", value: "7 - 10" },
    ],
    technicalDataNote: "Values are reference data for early-stage selection. Final thermal, fire, acoustic and moisture performance varies by density, thickness, facing and installed assembly; confirm the approved technical submittal before ordering.",
  },
  {
    slug: "glass-wool-duct-board", name: "Glass Wool Duct Board", category: "HVAC insulation", categorySlug: "hvac-insulation", family: "Glass mineral wool", image: images.glassWoolDuctBoard,
    shortDescription: "Rigid resin-bonded glass-wool board for duct thermal control, acoustic treatment and fire-conscious HVAC assemblies.",
    overview: "Glass wool duct board provides a more rigid material form for ductwork-related systems. It is selected in accordance with duct design, facing, handling needs and the project’s thermal and acoustic requirements.",
    idealFor: ["HVAC duct thermal and acoustic insulation, including AHU rooms", "RCC underdecks, masonry walls, facades, spandrels and drywall", "Cold storage, small-furnace and train-coach insulation assemblies"], keyBenefits: ["Low reference thermal conductivity at 25 deg C mean temperature", "Reference sound absorption up to NRC 0.95", "Rigid board format for less compression and sagging in selected applications", "Reference non-combustible material performance"], availableForms: ["Density range: 32 - 120 kg/m3", "Thickness range: 15 - 100 mm", "Standard width: 0.6 m; length: 1.2 m", "Plain boards or aluminium, metallised-polypropylene, tissue and glass-cloth facing options"], selectionNotes: ["Confirm board density, thickness and facing against the duct, acoustic and fire-performance requirements", "Coordinate board joints, fixings, vapour barrier and exposed-edge protection with the full assembly", "Verify the final offered product's approved technical submittal before ordering"], brochureCompany: "RAC Insutech",
    technicalData: [
      { description: "Material range and thermal performance", standard: "", unit: "", value: "", isSection: true },
      { description: "Material composition", standard: "", unit: "", value: "Resin-bonded glass wool" },
      { description: "Reference product range", standard: "", unit: "kg/m3 / mm", value: "Density 32 - 120; thickness 15 - 100" },
      { description: "Reference dimensions", standard: "", unit: "m", value: "Width 0.6; length 1.2" },
      { description: "Facing options", standard: "", unit: "", value: "Plain; aluminium, metallised-polypropylene, tissue or glass-cloth facings" },
      { description: "Reference standard", standard: "IS 8183", unit: "", value: "Applicable code reference" },
      { description: "Thermal conductivity at 25 deg C mean temperature", standard: "IS 8183 / IS 3346", unit: "W/m.K", value: "0.030 - 0.034" },
      { description: "Thermal resistance at specific thickness", standard: "", unit: "m2.K/W", value: "25 mm: 0.76 - 0.8; 50 mm: 1.52 - 1.6" },
      { description: "Noise reduction coefficient", standard: "ASTM C 423 / ISO 354", unit: "NRC", value: "0.65 - 0.95" },
      { description: "Fire, moisture and material properties", standard: "", unit: "", value: "", isSection: true },
      { description: "Non-combustibility", standard: "BS 476 Part 4 / IS 8183 / EN 13501", unit: "", value: "Non-combustible / incombustible; A1 reference classification" },
      { description: "Surface spread of flame", standard: "BS 476 Part 7", unit: "", value: "Nil; Class 1" },
      { description: "Fire propagation", standard: "BS 476 Parts 6 and 7", unit: "", value: "Class 0; index I <12; sub-index i1 <6" },
      { description: "Moisture content", standard: "IS 3144 / IS 8183", unit: "%", value: "<2" },
      { description: "Shot content", standard: "IS 3144 / IS 8183", unit: "", value: "Nil" },
      { description: "Sulphur and chloride", standard: "IS 3144 / IS 8183", unit: "", value: "Negligible" },
      { description: "Mould growth", standard: "IS 3144 / IS 8183", unit: "", value: "None" },
      { description: "Alkalinity", standard: "IS 8183", unit: "pH", value: "7 - 10" },
    ],
    technicalDataNote: "Values are reference data for early-stage selection. Final thermal, acoustic, fire and moisture performance varies by density, thickness, facing and installed assembly; confirm the approved technical submittal before ordering.",
  },
  {
    slug: "glass-wool-flexible-duct", name: "Glass Wool Flexible Duct", category: "HVAC insulation", categorySlug: "hvac-insulation", family: "Glass mineral wool", image: images.glassWoolFlexibleDuct,
    shortDescription: "Insulated flexible HVAC duct with a glass-wool layer, wire-helix core and reinforced vapour-barrier outer jacket.",
    overview: "Glass wool flexible duct is a flexible air-distribution connection for HVAC installations, commonly used between metal ducts and air terminals. Its layered construction combines a wire-helix inner core, a glass-wool insulation layer and a reinforced outer jacket, so duct diameter, run length, insulation, joints and support method should be selected as one complete system.",
    idealFor: ["Connecting grilles and diffusers to metal ducts", "Flexible HVAC distribution runs", "Insulated air-distribution connections where compact routing is required"], keyBenefits: ["Flexible connection around constrained HVAC routes", "Reference thermal conductivity and thermal-resistance values for the insulation layer", "Reinforced foil outer jacket that acts as a vapour barrier", "Tear- and handling-resistant outer construction"], availableForms: ["Insulated flexible duct density: 16 - 32 kg/m3", "Diameter range: 4 - 20 inch", "Length range: 10 - 25 ft", "25 mm insulation thickness on insulated duct configurations"], selectionNotes: ["Confirm duct diameter, run length, insulation and required airflow performance", "Coordinate supports, bends, joints and terminal connections to avoid excessive compression or kinking", "Verify the final offered duct configuration, fire requirements and approved technical submittal before ordering"], brochureCompany: "RAC Insutech",
    technicalData: [
      { description: "Duct construction and range", standard: "", unit: "", value: "", isSection: true },
      { description: "Insulated duct density", standard: "", unit: "kg/m3", value: "16 - 32" },
      { description: "Duct diameter", standard: "", unit: "inch", value: "4 - 20" },
      { description: "Duct length", standard: "", unit: "ft", value: "10 - 25" },
      { description: "Insulation thickness, insulated duct", standard: "", unit: "mm", value: "25" },
      { description: "Inner core", standard: "", unit: "", value: "Double-laminated film on coated steel-wire helix" },
      { description: "Outer jacket", standard: "", unit: "", value: "Aluminium or metallised foil with fibreglass-yarn reinforcement" },
      { description: "Outer-jacket function", standard: "", unit: "", value: "Vapour barrier; tear- and handling-resistant" },
      { description: "Thermal and material properties", standard: "", unit: "", value: "", isSection: true },
      { description: "Glass-wool thermal conductivity at 25 deg C mean temperature", standard: "", unit: "W/m.K", value: "0.032 - 0.039" },
      { description: "Thermal resistance of insulation", standard: "", unit: "m2.K/W", value: "0.64 - 0.78" },
      { description: "Temperature range", standard: "", unit: "deg C", value: "0 - 90" },
      { description: "Fire rating of glass-wool core", standard: "BS 476 Part 4 / IS 8183", unit: "", value: "Non-combustible" },
      { description: "Moisture content", standard: "IS 3144 / IS 8183", unit: "%", value: "<2" },
      { description: "Shot content", standard: "IS 3144 / IS 8183", unit: "", value: "Nil" },
      { description: "Sulphur and chloride", standard: "IS 3144 / IS 8183", unit: "", value: "Nil" },
      { description: "Mould growth", standard: "IS 3144 / IS 8183", unit: "", value: "None" },
      { description: "Alkalinity", standard: "IS 8183", unit: "pH", value: "7 - 10" },
    ],
    technicalDataNote: "Values are reference data for early-stage selection. Final HVAC performance depends on duct diameter, route, support spacing, insulation configuration, joints and installed assembly; confirm the approved technical submittal before ordering.",
  },
  {
    slug: "glass-wool-acoustic-board", name: "Glass Wool Acoustic Board", category: "Acoustic insulation", categorySlug: "acoustic-insulation", family: "Glass mineral wool", image: images.glassWoolAcousticBoard,
    shortDescription: "Dense resin-bonded glass-wool board for acoustic, thermal and fire-conscious building and HVAC assemblies.",
    overview: "Glass wool acoustic board is a rigid resin-bonded mineral-fibre panel for assemblies that require sound absorption alongside thermal and fire performance. It can be specified for ceilings, walls, duct systems and equipment areas when its thickness, density, facing and mounting detail are matched to the desired acoustic outcome.",
    idealFor: ["Underdecks, false ceilings and masonry-wall treatments", "HVAC duct thermal and acoustic systems, including AHU rooms", "Gensets, testing areas and mobility HVAC-duct applications"], keyBenefits: ["Reference acoustic performance with defined board and air-gap conditions", "Low reference thermal conductivity at 25 deg C mean temperature", "Dual-face foil and glass-cloth facing configuration", "Reference non-combustible material performance"], availableForms: ["Density range: 70 - 80 kg/m3", "Thicknesses: 25 - 50 mm", "Widths: 0.6 and 1.2 m; lengths: 1.2 and 2.5 m", "FSK facing on one side with black-glass-cloth facing on the other"], selectionNotes: ["Confirm the required NRC, installed air gap, thickness and exposed area for the acoustic objective", "Coordinate the board facing, fixings and joints with the HVAC or building assembly", "Use the final offered product's approved technical submittal for project approval"], brochureCompany: "RAC Insutech",
    technicalData: [
      { description: "Material range and thermal performance", standard: "", unit: "", value: "", isSection: true },
      { description: "Material composition", standard: "", unit: "", value: "Resin-bonded glass wool" },
      { description: "Reference product range", standard: "", unit: "kg/m3 / mm", value: "Density 70 - 80; thickness 25 - 50" },
      { description: "Reference dimensions", standard: "", unit: "m", value: "Width 0.6 or 1.2; length 1.2 or 2.5" },
      { description: "Facing configuration", standard: "", unit: "", value: "Foil-scrim-kraft one side; black glass cloth opposite side" },
      { description: "Reference standard", standard: "IS 8183", unit: "", value: "Applicable code reference" },
      { description: "Thermal conductivity at 25 deg C mean temperature", standard: "IS 8183 / IS 3346", unit: "W/m.K", value: "0.0306" },
      { description: "Thermal resistance", standard: "", unit: "m2.K/W", value: "0.8 - 1.6; calculated from thickness and thermal conductivity" },
      { description: "Noise reduction coefficient", standard: "ASTM C 423 / ISO 354", unit: "NRC", value: "0.65 at 25 mm; 0.75 with 35 mm air gap" },
      { description: "Fire, moisture and material properties", standard: "", unit: "", value: "", isSection: true },
      { description: "Non-combustibility", standard: "BS 476 Part 4 / IS 8183 / EN 13501", unit: "", value: "Non-combustible / incombustible; A1 reference classification" },
      { description: "Surface spread of flame", standard: "BS 476 Part 7", unit: "", value: "Nil; Class 1" },
      { description: "Fire propagation", standard: "BS 476 Parts 6 and 7", unit: "", value: "Class 0; index I <12; sub-index i1 <6" },
      { description: "Moisture content", standard: "IS 3144 / IS 8183", unit: "%", value: "<2" },
      { description: "Shot content", standard: "IS 3144 / IS 8183", unit: "", value: "Nil" },
      { description: "Sulphur and chloride", standard: "IS 3144 / IS 8183", unit: "", value: "Negligible" },
      { description: "Mould growth", standard: "IS 3144 / IS 8183", unit: "", value: "None" },
      { description: "Alkalinity", standard: "IS 8183", unit: "pH", value: "7 - 10" },
    ],
    technicalDataNote: "Values are reference data for early-stage selection. Final acoustic, thermal, fire and moisture performance varies by thickness, density, facing, air gap and installed assembly; confirm the approved technical submittal before ordering.",
  },
  {
    slug: "glass-wool-pipe-wrap", name: "Glass Wool Pipe Insulation", category: "Hot insulation", categorySlug: "hot-insulation", family: "Glass mineral wool", image: images.glassWoolPipe,
    shortDescription: "Resin-bonded glass-wool pipe sections and lamella mats for thermal, acoustic and fire-conscious mechanical services.",
    overview: "Glass wool pipe insulation is supplied as pre-formed pipe sections and flexible lamella mats for insulated HVAC and mechanical service lines. Selection begins with the pipe diameter, thickness and service condition, then confirms the facing, joint treatment and final outer protection required by the full installation.",
    idealFor: ["Chilled-water lines", "Hot-water lines", "Mechanical and utility pipework requiring shaped or flexible mineral-wool insulation"], keyBenefits: ["Pre-formed and flexible formats for different pipe diameters", "Low reference thermal conductivity at 25 deg C mean temperature", "Reference acoustic performance up to NRC 0.95", "Reference non-combustible material performance"], availableForms: ["Pipe sections: 80 kg/m3, 25 - 75 mm thickness, NB 25 - 450 mm, 1.2 m length", "Lamella mats: 80 kg/m3, 25 - 75 mm thickness, NB 350 - 1400 mm, 0.9 m length", "Plain pre-formed pipe sections or faced options", "Aluminium foil-scrim-kraft facing option"], selectionNotes: ["Confirm pipe NB, insulation thickness, format and final length for each line", "Coordinate joints, supports, moisture strategy and any protective outer finish", "Verify the final offered product's approved technical submittal before ordering"], brochureCompany: "RAC Insutech",
    technicalData: [
      { description: "Material range and thermal performance", standard: "", unit: "", value: "", isSection: true },
      { description: "Material composition", standard: "", unit: "", value: "Resin-bonded glass wool" },
      { description: "Pipe-section range", standard: "", unit: "kg/m3 / mm / NB", value: "Density 80; thickness 25 - 75; NB 25 - 450; length 1.2 m" },
      { description: "Lamella-mat range", standard: "", unit: "kg/m3 / mm / NB", value: "Density 80; thickness 25 - 75; NB 350 - 1400; length 0.9 m" },
      { description: "Facing options", standard: "", unit: "", value: "Plain pipe section or aluminium foil-scrim-kraft facing option" },
      { description: "Reference standard", standard: "IS 9842", unit: "", value: "Applicable code reference" },
      { description: "Thermal conductivity at 25 deg C mean temperature", standard: "IS 8183 / IS 3346", unit: "W/m.K", value: "0.031" },
      { description: "Thermal resistance", standard: "", unit: "m2.K/W", value: "Calculated from thickness, diameter and thermal conductivity" },
      { description: "Noise reduction coefficient", standard: "ASTM C 423 / ISO 354", unit: "NRC", value: "0.65 - 0.95" },
      { description: "Fire, moisture and material properties", standard: "", unit: "", value: "", isSection: true },
      { description: "Non-combustibility", standard: "BS 476 Part 4 / IS 8183 / EN 13501", unit: "", value: "Non-combustible / incombustible; A1 reference classification" },
      { description: "Surface spread of flame", standard: "BS 476 Part 7", unit: "", value: "Nil; Class 1" },
      { description: "Fire propagation", standard: "BS 476 Parts 6 and 7", unit: "", value: "Class 0; index I <12; sub-index i1 <6" },
      { description: "Moisture content", standard: "IS 3144 / IS 8183", unit: "%", value: "<2" },
      { description: "Shot content", standard: "IS 3144 / IS 8183", unit: "", value: "Nil" },
      { description: "Sulphur and chloride", standard: "IS 3144 / IS 8183", unit: "", value: "Negligible" },
      { description: "Mould growth", standard: "IS 3144 / IS 8183", unit: "", value: "None" },
      { description: "Alkalinity", standard: "IS 8183", unit: "pH", value: "7 - 10" },
    ],
    technicalDataNote: "Values are reference data for early-stage selection. Final thermal, acoustic, fire and moisture performance varies by pipe size, thickness, facing and installed assembly; confirm the approved technical submittal before ordering.",
  },
  {
    slug: "rock-wool-slab", name: "Rock Wool Slab", category: "Hot insulation", categorySlug: "hot-insulation", family: "Stone mineral wool", image: images.rockWoolSlab,
    shortDescription: "Semi-rigid and rigid resin-bonded stone-wool slabs for thermal, fire-conscious building and industrial assemblies.",
    overview: "Rock wool slabs are resin-bonded stone-fibre boards used for thermal insulation in building and industrial assemblies. The slab format can be supplied plain or faced, with its density, thickness, surface treatment and complete installation detail selected around the target thermal, fire and moisture conditions.",
    idealFor: ["Metal roofs and walls, RCC underdecks and overdecks", "Masonry walls, drywall and façade assemblies", "Furnaces, tanks, boilers, appliances and acoustic enclosures"], keyBenefits: ["Reference non-combustible material performance", "Reference thermal conductivity at 200 deg C mean temperature", "Semi-rigid and rigid slab formats with facing options", "Stone-wool construction for building and industrial applications"], availableForms: ["Density range: 40 - 180 kg/m3", "Thickness: 25 - 150 mm; width: 0.6 m; length: 0.6 - 1.2 m", "Plain or faced slabs", "Aluminium and black-glass-tissue facing options"], selectionNotes: ["Confirm density, thickness, facing and final slab dimensions for the required thermal and mechanical performance", "Coordinate fixing, joint treatment and any protective outer layer with the full assembly", "Verify final fire, water-vapour, water-absorption and installation requirements against the approved technical submittal"], brochureCompany: "RAC Insutech",
    technicalData: [
      { description: "Material range and thermal performance", standard: "", unit: "", value: "", isSection: true },
      { description: "Material composition", standard: "", unit: "", value: "Resin-bonded stone wool slab" },
      { description: "Reference product range", standard: "", unit: "kg/m3 / mm", value: "Density 40 - 180; thickness 25 - 150" },
      { description: "Reference dimensions", standard: "", unit: "m", value: "Width 0.6; length 0.6 - 1.2" },
      { description: "Facing options", standard: "", unit: "", value: "Plain; aluminium or black-glass-tissue options" },
      { description: "Reference standards", standard: "IS 8183 / IS 3144 / ASTM C 612", unit: "", value: "Applicable code references" },
      { description: "Thermal conductivity at 200 deg C mean temperature", standard: "IS 8183", unit: "W/m.K", value: "0.059 - 0.074" },
      { description: "Thermal resistance", standard: "", unit: "m2.K/W", value: "Calculated from thickness and thermal conductivity" },
      { description: "Fire and moisture properties", standard: "", unit: "", value: "", isSection: true },
      { description: "Non-combustibility", standard: "BS 476 Part 4 / IS 8183", unit: "", value: "Non-combustible / incombustible" },
      { description: "Surface-burning characteristics", standard: "ASTM E 84 / UL 723", unit: "", value: "Flame spread index <=25; smoke developed index <=50" },
      { description: "Water-vapour sorption", standard: "ASTM C 1104 / ASTM C 1104M", unit: "% by volume", value: "<5" },
      { description: "Water absorption", standard: "BS 2972 Part 11", unit: "kg/m2", value: "<0.5" },
      { description: "Durability and material properties", standard: "", unit: "", value: "", isSection: true },
      { description: "Shot content", standard: "IS 3144 / IS 8183", unit: "%", value: "<25" },
      { description: "Sulphur and chloride", standard: "IS 3144 / IS 8183", unit: "ppm / %", value: "Chloride <20 ppm; sulphur <0.2%" },
      { description: "Mould growth", standard: "IS 3144 / IS 8183", unit: "", value: "No fungal growth" },
      { description: "Alkalinity", standard: "IS 8183", unit: "pH", value: "7 - 10" },
    ],
    technicalDataNote: "Values are reference data for early-stage selection. Final thermal, fire and moisture performance varies by density, thickness, facing and installed assembly; confirm the approved technical submittal before ordering.",
  },
  {
    slug: "rock-wool-pipe-section", name: "Rock Wool Pipe Section", category: "Pipe insulation", categorySlug: "pipe-insulation", family: "Stone mineral wool", image: images.rockWoolPipe,
    shortDescription: "Pre-formed stone-wool pipe sections for thermal, fire-conscious steam and process pipeline insulation.",
    overview: "Rock wool pipe sections are shaped stone-wool insulation elements for industrial piping. They provide consistent coverage around steam and process lines when the nominal bore, insulation thickness, density, joint detail and final protective cladding are selected for the actual operating condition.",
    idealFor: ["Steam pipelines", "Process pipelines", "Industrial utility and OEM pipework"], keyBenefits: ["Pre-formed geometry for round pipework", "Reference thermal conductivity at 200 deg C mean temperature", "Plain or aluminium-faced options", "Reference non-combustible material performance"], availableForms: ["Density range: 100 - 160 kg/m3", "Thicknesses: 25 - 100 mm", "Nominal bore: 15 - 600 mm", "Lengths: 1.2 - 1.25 m; plain or aluminium foil-scrim-kraft facing"], selectionNotes: ["Confirm pipe NB, thickness, density and section length for each pipeline", "Coordinate joints, supports, expansion details and protective cladding with the complete piping system", "Verify final operating conditions and the approved technical submittal before ordering"], brochureCompany: "RAC Insutech",
    technicalData: [
      { description: "Material range and thermal performance", standard: "", unit: "", value: "", isSection: true },
      { description: "Material composition", standard: "", unit: "", value: "Stone-wool pipe section" },
      { description: "Reference product range", standard: "", unit: "kg/m3 / mm / NB", value: "Density 100 - 160; thickness 25 - 100; NB 15 - 600" },
      { description: "Reference length", standard: "", unit: "m", value: "1.2 - 1.25" },
      { description: "Facing options", standard: "", unit: "", value: "Plain or aluminium foil-scrim-kraft facing" },
      { description: "Reference standards", standard: "IS 9842 / ASTM C 547", unit: "", value: "Applicable code references" },
      { description: "Thermal conductivity at 200 deg C mean temperature", standard: "IS 9842 / ASTM C 547", unit: "W/m.K", value: "0.065" },
      { description: "Thermal resistance", standard: "", unit: "m2.K/W", value: "Calculated from thickness and thermal conductivity" },
      { description: "Fire and moisture properties", standard: "", unit: "", value: "", isSection: true },
      { description: "Non-combustibility", standard: "BS 476 Part 4 / IS 9842", unit: "", value: "Non-combustible / incombustible" },
      { description: "Surface-burning characteristics", standard: "ASTM E 84", unit: "", value: "Flame spread index <=25; smoke developed index <=50" },
      { description: "Water-vapour sorption", standard: "ASTM C 1104 / ASTM C 1104M / BS 2972", unit: "% by volume", value: "<5" },
      { description: "Water absorption", standard: "BS 2972 Part 11", unit: "kg/m2", value: "<0.5" },
      { description: "Durability and material properties", standard: "", unit: "", value: "", isSection: true },
      { description: "Shot content", standard: "IS 9842", unit: "%", value: "<25" },
      { description: "Sulphur and chloride", standard: "IS 9842", unit: "ppm / %", value: "Chloride <20 ppm; sulphur <0.2%" },
      { description: "Mould growth", standard: "IS 9842", unit: "", value: "No fungal growth" },
      { description: "Alkalinity", standard: "IS 9842", unit: "pH", value: "7 - 10" },
    ],
    technicalDataNote: "Values are reference data for early-stage selection. Final thermal, fire and moisture performance varies by density, thickness, facing and installed piping assembly; confirm the approved technical submittal before ordering.",
  },
  {
    slug: "rock-wool-acoustic-panel", name: "Rock Wool Acoustic Panel", category: "Acoustic insulation", categorySlug: "acoustic-insulation", family: "Stone mineral wool", image: images.rockWoolAcoustic,
    shortDescription: "Dense mineral-wool board for sound-control walls, ceilings and equipment enclosures.",
    overview: "Rock wool acoustic panels are used as a sound-absorbing layer within a complete assembly. The surrounding construction, air gaps, perforated facings and sealing details determine the overall result.",
    idealFor: ["Acoustic enclosures", "Ceiling systems", "Partition build-ups"], keyBenefits: ["Rigid panel handling", "Mineral-wool acoustic layer", "Supports system-led sound control"], availableForms: ["Plain panels", "Faced panels", "Custom cut sizes"], selectionNotes: ["Define absorption or isolation objective", "Coordinate the complete assembly", "Review visible-facing requirements"], brochureCompany: "RAC Insutech",
  },
  {
    slug: "ceramic-fibre-blanket", name: "Ceramic Fibre Blanket", category: "High-temperature insulation", categorySlug: "high-temperature-insulation", family: "High-temperature fibre", image: images.ceramicFibre,
    shortDescription: "Flexible ceramic-fibre blankets in alumina-silica and alumina-silica-zirconia configurations for high-temperature insulation.",
    overview: "Ceramic Fibre Blanket is a flexible refractory-insulation material for demanding high-temperature equipment. The alumina-silica configuration is classified to 1,260 deg C, while the alumina-silica-zirconia configuration is classified to 1,430 deg C. Final selection must account for the continuous operating temperature, density, mechanical protection and the complete installation design.",
    idealFor: ["HRSG ducts, industrial and commercial chimneys", "Boiler, furnace, heater and kiln back-up linings", "Pipe wraps, metal launders and welding stress-relief work"],
    keyBenefits: ["Low thermal conductivity and heat storage", "Flexible, resilient blanket handling", "Resists thermal shock and supports elevated-temperature service"],
    availableForms: ["Reference densities: 64, 96, 128 and 160 kg/m3", "Blankets in project-specified thicknesses", "Alumina-silica or alumina-silica-zirconia configurations"],
    selectionNotes: ["Match the configuration to the required classification and continuous-use temperature", "Confirm density, thickness and conductivity against the duty conditions", "Review refractory-system safety, anchors, facings and mechanical protection"],
    technicalData: [
      { description: "Reference product configurations", standard: "", unit: "", value: "", isSection: true },
      { description: "Material composition", standard: "", unit: "", value: "Alumina-silica / Alumina-silica-zirconia" },
      { description: "Colour", standard: "", unit: "", value: "White / White" },
      { description: "Classification temperature", standard: "", unit: "deg C (deg F)", value: "1,260 (2,300) / 1,430 (2,600)" },
      { description: "Continuous-use temperature", standard: "", unit: "deg C (deg F)", value: "1,180 (2,150) / 1,315 (2,400)" },
      { description: "Melting point", standard: "", unit: "deg C (deg F)", value: "1,760 (3,200) / 1,760 (3,200)" },
      { description: "Reference bulk densities", standard: "", unit: "kg/m3 (pcf)", value: "64, 96, 128, 160 (4, 6, 8, 10)" },
      { description: "Tensile strength by density", standard: "EN 1094-1", unit: "kPa (psi)", value: "64: 30 (4.35); 96: 70 (10.15); 128: 90 (13.05); 160: 110 (15.95)" },
      { description: "Typical chemical composition", standard: "", unit: "%", value: "Alumina-silica: SiO2 52-58, Al2O3 42-48; alumina-silica-zirconia: SiO2 48-52, Al2O3 33-37, ZrO2 13-17" },
      { description: "Thermal conductivity (reference values)", standard: "", unit: "", value: "", isSection: true },
      { description: "Alumina-silica at 200 / 400 / 600 deg C", standard: "ASTM C201", unit: "W/m.K", value: "64 / 96 / 128 kg/m3: 0.06 / 0.06 / 0.05 | 0.11 / 0.09 / 0.08 | 0.19 / 0.16 / 0.13" },
      { description: "Alumina-silica at 800 / 1,000 deg C", standard: "ASTM C201", unit: "W/m.K", value: "64 / 96 / 128 kg/m3: 0.31 / 0.25 / 0.19 | 0.45 / 0.36 / 0.27" },
      { description: "Alumina-silica-zirconia at 200 / 400 / 600 deg C", standard: "ASTM C201", unit: "W/m.K", value: "96 / 128 kg/m3: 0.07 / 0.05 | 0.10 / 0.08 | 0.16 / 0.14" },
      { description: "Alumina-silica-zirconia at 800 / 1,000 / 1,200 deg C", standard: "ASTM C201", unit: "W/m.K", value: "96 / 128 kg/m3: 0.24 / 0.19 | 0.36 / 0.27 | 0.51 / 0.36" },
    ],
    technicalDataNote: "Reference values apply to the stated ceramic-fibre configuration and density. Confirm final performance, thickness, installation method and project suitability against current verified documentation before ordering.",
    brochureCompany: "RAC Insutech",
  },
  {
    slug: "xps-insulation-board", name: "XPS Insulation Board", category: "Cold insulation", categorySlug: "cold-insulation", family: "Rigid thermal board", image: images.xpsBoard,
    shortDescription: "Rigid, closed-cell XPS thermal boards for moisture-conscious roof, wall, floor and cold-service assemblies.",
    overview: "XPS insulation board is a rigid, closed-cell extruded-polystyrene thermal board for building-envelope and selected cold-service applications. Its compact board format supports durable thermal layers in roof, wall and floor build-ups when the board thickness, edge profile, waterproofing and final protective layers are selected for the project.",
    idealFor: ["Overdeck roofs and accessible terraces", "External and internal wall insulation systems", "Floors, foundations and selected cold-service support areas"], keyBenefits: ["Closed-cell rigid-board construction", "Low reference thermal conductivity at 25 deg C", "Minimum compressive strength for load-conscious assemblies", "Low reference water absorption by submersion"], availableForms: ["Standard board size: 1250 x 600 mm", "25, 30, 40, 50, 75 and 100 mm thicknesses", "Square edges in 25 and 30 mm thicknesses", "Shiplap edges in 40, 50, 75 and 100 mm thicknesses"], selectionNotes: ["Confirm thickness, loading, edge profile and the specified board grade for the application", "For roofs, coordinate slope, waterproofing, vapour barrier, joints and the final protective screed or finish", "Install boards with staggered joints and confirm the complete wall, floor or roof system before ordering"], brochureCompany: "RAC Insutech",
    technicalData: [
      { description: "Physical properties", standard: "", unit: "", value: "", isSection: true },
      { description: "Density", standard: "ASTM D 1622", unit: "kg/m3", value: "32 - 36" },
      { description: "Compressive strength at 10% deflection", standard: "ASTM D 1621", unit: "kPa / N/mm2", value: "276 minimum / 0.276" },
      { description: "Thermal conductivity at 25 deg C", standard: "IS 3346", unit: "W/m-K / Btu-in/ft2-h-deg F", value: "0.028 / 0.194" },
      { description: "Thermal conductivity at 10 deg C", standard: "IS 3346", unit: "W/m-K / Btu-in/ft2-h-deg F", value: "0.014 / 0.097" },
      { description: "Water vapour permeability", standard: "ASTM E 96", unit: "mg/hmPa", value: "0.0037 minimum" },
      { description: "Water absorption by submersion (28 days)", standard: "ASTM D 2842", unit: "Volume %", value: "0.5 maximum" },
      { description: "Dimensional stability", standard: "SPL test method", unit: "%", value: "2 maximum" },
      { description: "Flammability", standard: "DIN 4102, Part 1", unit: "", value: "B2" },
      { description: "Reference compliance statement", standard: "ISO 4898:2008 / ASTM C 578-08b", unit: "Type", value: "VI requirements" },
      { description: "Packing details (per bag)", standard: "", unit: "", value: "", isSection: true },
      { description: "Standard board size", standard: "", unit: "mm", value: "1250 x 600" },
      { description: "25 mm board, square edge", standard: "", unit: "Boards / m2 / m3 / ft3", value: "18 / 13.5 / 0.3375 / 11.92" },
      { description: "30 mm board, square edge", standard: "", unit: "Boards / m2 / m3 / ft3", value: "15 / 11.25 / 0.3375 / 11.92" },
      { description: "40 mm board, shiplap edge", standard: "", unit: "Boards / m2 / m3 / ft3", value: "10 / 7.5 / 0.3 / 10.59" },
      { description: "50 mm board, shiplap edge", standard: "", unit: "Boards / m2 / m3 / ft3", value: "8 / 6 / 0.3 / 10.59" },
      { description: "75 mm board, shiplap edge", standard: "", unit: "Boards / m2 / m3 / ft3", value: "6 / 4.5 / 0.3375 / 11.92" },
      { description: "100 mm board, shiplap edge", standard: "", unit: "Boards / m2 / m3 / ft3", value: "5 / 3.75 / 0.375 / 13.24" },
    ],
    technicalDataNote: "Values are reference data for early-stage selection. Confirm the exact board grade, density, thickness, edge profile and approved technical submittal before ordering.",
  },
  {
    slug: "pir-pur-insulation-panel", name: "PIR / PUR Insulation Panel", category: "Cold insulation", categorySlug: "cold-insulation", family: "Rigid thermal board", image: images.pirPurPanel,
    shortDescription: "High-efficiency rigid foam board family for specified wall, roof and panel systems.",
    overview: "PIR and PUR insulation panels form part of highly specified building-envelope and controlled-environment assemblies. Project requirements should define the exact product, facing, joint detail and fire-performance documentation.",
    idealFor: ["Roof panels", "Cold rooms", "Wall and sandwich-panel systems"], keyBenefits: ["Rigid panel format", "Faced-board options", "Efficient use of build-up depth"], availableForms: ["Foil-faced boards", "Panel cores", "Cut components"], selectionNotes: ["Use verified manufacturer approval data", "Coordinate joints and flashings", "Review fire and compliance requirements"], brochureCompany: "RAC Insutech",
  },
  {
    slug: "eps-insulation-board", name: "EPS Insulation Board", category: "Cold insulation", categorySlug: "cold-insulation", family: "Rigid thermal board", image: images.epsBoard,
    shortDescription: "Lightweight expanded-polystyrene board for selected building and packaging insulation applications.",
    overview: "EPS insulation boards are a lightweight board option used in selected building assemblies. Material grade, density, finish and installation details should align with the project’s exact thermal, structural and exposure needs.",
    idealFor: ["Wall systems", "Floor build-ups", "Protected roof insulation"], keyBenefits: ["Lightweight boards", "Easy cutting and handling", "Useful in specified building assemblies"], availableForms: ["Plain boards", "Cut shapes", "Project-specific sizes"], selectionNotes: ["Confirm the specified grade", "Protect from UV and solvents", "Coordinate with the final finish"], brochureCompany: "RAC Insutech",
  },
  {
    slug: "foil-bubble-insulation", name: "Foil Bubble Insulation", category: "Roof & PEB insulation", categorySlug: "roof-peb-insulation", family: "Reflective roof system", image: images.foilBubble,
    shortDescription: "Reflective aluminium-foil bubble insulation for underdeck, wall and roof assemblies.",
    overview: "Foil bubble insulation is a radiant heat-reflective material made from polyethylene air-bubble film laminated with aluminium foil on one or both sides. Its low-mass reflective construction is designed for roof, wall and cladding assemblies where an air space is included as part of the build-up.",
    idealFor: ["Underdeck and wall insulation", "PEBs, industrial and poultry sheds", "Warehouses, airports, textile and manufacturing facilities"], keyBenefits: ["Documented high foil reflectivity and low emissivity", "Non-toxic, fibre-free and chemically inert", "Resists corrosion, fungus, puncture and tear", "Lightweight rolls for roof and wall assemblies"], availableForms: ["75 m rolls x 1250 mm width", "4 mm and 8 mm thicknesses", "230, 300 and 400 GSM ranges", "One- or two-side aluminium foil, metPET, five-layer and seven-layer bubble options"], selectionNotes: ["Maintain the required air space for reflective performance", "Confirm the roof or wall build-up, facing and GSM", "Verify final material configuration and approved technical data before ordering"], brochureCompany: "RAC Insutech",
    technicalData: [
      { description: "Reflectivity, gridline pattern", standard: "ASTM C 1371", unit: "%", value: "99%" },
      { description: "Reflectivity, circular pattern", standard: "ASTM C 1371", unit: "%", value: "96%" },
      { description: "Emissivity, gridline pattern", standard: "ASTM C 1371", unit: "", value: "0.01" },
      { description: "Emissivity, circular pattern", standard: "ASTM C 1371", unit: "", value: "0.04" },
      { description: "Corrosion resistance*", standard: "ASTM D 3310", unit: "", value: "No visible sign of corrosion" },
      { description: "Fire propagation*", standard: "BS 476 Part 6:1989", unit: "", value: "Complied, Class 0" },
      { description: "Surface spread of flame*", standard: "BS 476 Part 7:1997", unit: "", value: "Complied, Class 1" },
      { description: "Thermal resistance*", standard: "ASTM C 236", unit: "K.m2/W", value: "13.70" },
      { description: "Puncture resistance*", standard: "TAPPI T 803", unit: "Joules", value: "39.24" },
      { description: "Fungus resistance*", standard: "ASTM C 1338", unit: "", value: "Pass" },
      { description: "Water-vapour transmission, 7 days*", standard: "ASTM E 96", unit: "", value: "Negligible" },
      { description: "Water-vapour transmission, 28 days*", standard: "ASTM E 96", unit: "", value: "Negligible" },
    ],
    technicalDataNote: "*Reference values are supplied for the specified product format only. Reflective-system performance depends on the installed air space, configuration and final approved material.",
  },
  {
    slug: "epe-foil-foam", name: "EPE Foil Foam Insulation", category: "Roof & PEB insulation", categorySlug: "roof-peb-insulation", family: "Reflective roof system", image: images.epeFoilFoam,
    shortDescription: "Foil-faced polyethylene foam for roof, wall and service insulation detailing.",
    overview: "EPE foil foam combines a lightweight foam core with reflective facings. It can be used as part of a broader roof, wall or service-insulation detail where installation method and surrounding layers are defined.",
    idealFor: ["Metal roofs", "Wall linings", "Service protection layers"], keyBenefits: ["Lightweight flexible material", "Reflective face options", "Straightforward roll handling"], availableForms: ["Foil-faced rolls", "Plain foam rolls", "Laminated combinations"], selectionNotes: ["Confirm overlap direction", "Coordinate tape system", "Protect exposed edges"], brochureCompany: "RAC Insutech",
  },
  {
    slug: "aluminium-gi-ss-cladding", name: "Aluminium / GI / SS Cladding", category: "Cladding", categorySlug: "cladding", family: "System protection", image: images.metalCladding,
    shortDescription: "Protective outer cladding for selected pipe, equipment and industrial insulation systems.",
    overview: "Metal cladding provides the protective outer layer for many industrial insulation systems. Material choice, thickness, jointing, fastening and weather detailing should be engineered around the service environment and maintenance needs.",
    idealFor: ["Outdoor pipework", "Equipment insulation", "Industrial services"], keyBenefits: ["Durable external protection", "Clean professional finish", "Compatible with industrial insulation build-ups"], availableForms: ["Aluminium sheets", "GI sheets", "Stainless steel sheets and accessories"], selectionNotes: ["Confirm corrosion environment", "Plan expansion and drainage", "Coordinate bands, screws and overlap directions"], brochureCompany: "RAC Insutech",
  },
  {
    slug: "aerogel-insulation-blanket", name: "Aerogel Insulation Blanket", category: "High-temperature insulation", categorySlug: "high-temperature-insulation", family: "Advanced thermal insulation", image: images.aerogel,
    shortDescription: "Thin, flexible aerogel insulation blanket with an integrated vapour barrier for cryogenic and dual-temperature industrial service.",
    overview: "Aerogel Insulation Blanket is a flexible, hydrophobic insulation blanket for cold, cryogenic and dual-temperature applications. Its thin blanket construction and integrated vapour barrier support insulation of pipes, vessels, equipment and fittings where geometry, condensation control and installation depth require detailed consideration.",
    idealFor: ["Cryogenic and dual-temperature pipes, vessels and fittings", "Offshore, oil and gas, process and industrial facilities", "Complex equipment geometry and multi-layer insulation assemblies"],
    keyBenefits: ["Low reference thermal conductivity across cryogenic to elevated temperatures", "Hydrophobic blanket with an integrated zero-perm vapour barrier", "Flexible, thin material for detailed industrial geometries"],
    availableForms: ["Sheets in rolls", "5, 10 and 20 mm thicknesses", "Nominal roll width: 1.5 m"],
    selectionNotes: ["Confirm the operating-temperature envelope and the complete vapour-control design", "For service below -180 deg C, review the insulation system and installation workmanship in detail", "Protect the external insulation layer with suitable jacketing or cladding for the exposure condition"],
    technicalData: [
      { description: "Product and application reference", standard: "", unit: "", value: "", isSection: true },
      { description: "Material type", standard: "", unit: "", value: "Flexible aerogel insulation blanket with integrated zero-perm vapour barrier" },
      { description: "Product colour", standard: "", unit: "", value: "Grey" },
      { description: "Reference product range", standard: "", unit: "mm / m", value: "Sheets in rolls; thicknesses 5, 10 and 20; nominal width 1.5" },
      { description: "Reference applications", standard: "", unit: "", value: "Cold, cryogenic and dual-temperature insulation of pipes, vessels, equipment and fittings" },
      { description: "Reference compliance", standard: "ASTM C1728", unit: "", value: "Type I, Grade 1B and Type IV, Grade 1A" },
      { description: "Thermal performance", standard: "", unit: "", value: "", isSection: true },
      { description: "Service temperature", standard: "ASTM C411", unit: "deg C (deg F)", value: "-180 (-292) to 250 (482)" },
      { description: "Declared thermal conductivity", standard: "ASTM C177", unit: "W/m.K", value: "At -129 / -73.3 / -17.8 / 23.9 / 37.8 / 93.3 / 149 / 204 deg C: 0.014 / 0.015 / 0.016 / 0.017 / 0.017 / 0.019 / 0.025 / 0.029" },
      { description: "Linear shrinkage under soaking heat", standard: "ASTM C356", unit: "%", value: "<2 in width and length" },
      { description: "Surface burning characteristics", standard: "ASTM E84", unit: "", value: "Flame spread index <=25; smoke developed index <=50" },
      { description: "Moisture and corrosion reference", standard: "", unit: "", value: "", isSection: true },
      { description: "Water-vapour sorption", standard: "ASTM C1104", unit: "% by weight", value: "<=5" },
      { description: "Integrated vapour-barrier permeance", standard: "ASTM E96", unit: "perm", value: "0.00" },
      { description: "Water resistance", standard: "ASTM C1763", unit: "", value: "Hydrophobic; water absorption pass" },
      { description: "Corrosiveness to steel", standard: "ASTM C1617, Procedure A", unit: "", value: "Pass" },
      { description: "Stress corrosion cracking", standard: "ASTM C692 / ASTM C795", unit: "", value: "Pass, no cracks" },
      { description: "Physical and handling reference", standard: "", unit: "", value: "", isSection: true },
      { description: "Nominal density", standard: "ASTM C303", unit: "kg/m3 (lb/ft3)", value: "170 (10.6)" },
      { description: "Compressive strength at 10% compression", standard: "ASTM C165", unit: "kPa (psi)", value: ">=34.5 (>=5)" },
      { description: "Flexibility of insulation blankets", standard: "ASTM C1101", unit: "", value: "Flexible" },
      { description: "Fungal growth", standard: "ASTM C1338", unit: "", value: "No growth" },
      { description: "Weather, storage and shelf life", standard: "", unit: "", value: "Use adequate external jacketing or cladding for industrial exposure; store indoors, clean and dry, away from direct sunlight; maximum reference storage period 3 years" },
    ],
    technicalDataNote: "Reference values are supplied for the stated aerogel blanket configuration only. Confirm the approved product grade, insulation-system design, exposure protection and current technical documentation before ordering or installation.",
    brochureCompany: "RAC Insutech",
  },
  {
    slug: "mass-loaded-vinyl-barrier", name: "Mass Loaded Vinyl Barrier", category: "Acoustic insulation", categorySlug: "acoustic-insulation", family: "Acoustic barrier layer", image: images.massLoadedVinyl,
    shortDescription: "Flexible dense barrier layer for acoustic assemblies where sound isolation is a stated design objective.",
    overview: "Mass loaded vinyl is commonly considered as one layer in an acoustic build-up. Its role should be assessed with the surrounding panels, seals, gaps and structural connection details rather than as a stand-alone sound-control solution.",
    idealFor: ["Acoustic partitions", "Equipment enclosures", "Service and room isolation details"], keyBenefits: ["Flexible barrier-layer format", "Can be integrated into layered assemblies", "Compact sheet or roll handling"], availableForms: ["Rolls", "Cut sheets", "Laminated assemblies"], selectionNotes: ["Define isolation versus absorption requirement", "Coordinate perimeter seals", "Confirm facing and fire requirements"], brochureCompany: "RAC Insutech",
  },
  {
    slug: "polyester-acoustic-panel", name: "Polyester Acoustic Panel", category: "Acoustic insulation", categorySlug: "acoustic-insulation", family: "Acoustic panel", image: images.polyesterAcoustic,
    shortDescription: "Lightweight panel option for interior acoustic treatment and equipment-room assemblies.",
    overview: "Polyester acoustic panels are considered for sound-absorption treatments in interiors and equipment spaces. The final result depends on panel placement, exposed area, fixing, backing and the project’s desired acoustic outcome.",
    idealFor: ["Office and interior treatments", "Equipment rooms", "Acoustic feature assemblies"], keyBenefits: ["Lightweight panel handling", "Clean panel format", "Works within a system-led acoustic design"], availableForms: ["Plain panels", "Faced panels", "Custom-cut shapes"], selectionNotes: ["Confirm the acoustic objective", "Coordinate visible finishes", "Check location-specific compliance needs"], brochureCompany: "RAC Insutech",
  },
  {
    slug: "thermal-insulation-jacket", name: "Thermal Insulation Jacket", category: "Cladding", categorySlug: "cladding", family: "Removable system protection", image: images.thermalJacket,
    shortDescription: "Removable outer-jacket approach for valves, equipment and service points that require maintenance access.",
    overview: "Thermal insulation jackets form a removable insulation approach for equipment and details needing periodic access. The jacket design should be developed around geometry, fastening, safe handling and the required insulation core.",
    idealFor: ["Valves and flanges", "Maintenance-access equipment", "Irregular equipment geometry"], keyBenefits: ["Supports repeat maintenance access", "Adaptable to detailed geometry", "Complements equipment insulation systems"], availableForms: ["Custom jackets", "Removable covers", "Fastened equipment wraps"], selectionNotes: ["Survey final geometry", "Confirm access frequency", "Select suitable insulation core and outer fabric"], brochureCompany: "RAC Insutech",
  },
  {
    slug: "water-tank-cover", name: "Water Tank Cover", category: "Water Tank Cover", categorySlug: "water-tank-cover", family: "Custom tank insulation cover", image: images.waterTankCover,
    shortDescription: "Custom-fitted removable insulation cover for water-storage tanks, offered with XLPE or foil-bubble insulation constructions.",
    overview: "RAC Water Tank Cover is a made-to-measure external insulation cover for water-storage tanks. It wraps the tank body with a selected reflective insulation construction to help limit solar heat gain and heat absorption at the tank surface. The cover is developed around the tank geometry, connections and access requirements, using removable panels or a strapped wrap system for practical installation and maintenance.",
    idealFor: ["Vertical and horizontal cylindrical water-storage tanks", "Square, rectangular and modular-panel tanks", "Conical-top and dome-top tanks", "Residential, commercial and industrial rooftop water tanks"],
    keyBenefits: ["Helps reduce radiant solar heat gain at the tank surface", "Supports more stable stored-water temperature in exposed locations", "Custom fit around tank shape, piping, access points and supports", "Removable strap or panel system for installation and maintenance", "Reflective outer facing selected for the exposure and required finish", "Available in XLPE and foil-bubble insulation constructions"],
    availableForms: ["XLPE closed-cell insulation with aluminium-foil facing", "XLPE closed-cell insulation with GC cloth protective facing", "Foil-bubble insulation with aluminium-foil facing", "Vertical cylindrical, horizontal cylindrical, square / rectangular, conical-top and modular / panel tank cover designs", "Custom cut, strapped or panelled cover sets made to the measured tank"],
    selectionNotes: ["Measure the tank diameter or length, height, roof profile and all pipe, manhole and ladder clearances", "Select XLPE or foil-bubble construction according to the required build-up, facing and project budget", "Confirm the final insulation thickness, external-facing requirement and fastening arrangement before manufacture", "For outdoor installations, verify the cover detailing, water-shedding direction and exposure suitability for the selected facing", "Confirm the final design from the tank survey and approved RAC offer before ordering"],
    brochureCompany: "RAC Insutech",
    technicalData: [
      { description: "Product type", standard: "RAC measured cover design", unit: "", value: "External, removable insulation cover for water-storage tanks" },
      { description: "Insulation-core options", standard: "Selected RAC construction", unit: "", value: "Closed-cell XLPE insulation or foil-bubble insulation" },
      { description: "Facing options", standard: "Selected RAC construction", unit: "", value: "Aluminium foil; GC cloth protective facing for XLPE construction" },
      { description: "Tank geometry", standard: "Site measurement", unit: "", value: "Vertical / horizontal cylindrical, square / rectangular, conical-top or modular-panel tank" },
      { description: "Cover configuration", standard: "RAC measured cover design", unit: "", value: "Custom wrap, removable panels and/or strap-fastened cover set" },
      { description: "Site details to confirm", standard: "Site measurement", unit: "", value: "Tank dimensions, roof profile, access openings, piping, support legs and clearance requirements" },
      { description: "Exterior exposure", standard: "Project requirement", unit: "", value: "Confirm facing, water-shedding detail, fastening and service exposure for the final installation" },
    ],
    technicalDataNote: "This custom cover is manufactured to the surveyed tank and selected material construction. Final performance depends on the tank condition, cover fit, insulation thickness, facing, installation details and site exposure. Confirm the approved RAC drawing and offer before manufacture.",
  },
];

export const categories = Array.from(new Map(catalogue.map((product) => [product.categorySlug, { name: product.category, slug: product.categorySlug }])).values());

export const featuredProducts = catalogue.slice(0, 6);

export function getProduct(slug: string) {
  return catalogue.find((product) => product.slug === slug);
}
