import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

import { catalogue } from "../lib/catalogue";
import { quotationVariants } from "../lib/quotations/catalogue";

type SqlValue = string | number | boolean | null | undefined;

const outputPath = resolve("supabase/migrations/20260830000017_seed_v2_catalogue_and_rate_cards.sql");

function value(input: SqlValue) {
  if (input === null || input === undefined) return "null";
  if (typeof input === "number") return Number.isFinite(input) ? String(input) : "null";
  if (typeof input === "boolean") return input ? "true" : "false";
  return `'${input.replaceAll("'", "''")}'`;
}

function json(input: unknown) {
  return `${value(JSON.stringify(input))}::jsonb`;
}

function rows(values: string[]) {
  return values.map((entry) => `  ${entry}`).join(",\n");
}

const categories = [...new Map(catalogue.map((product) => [product.categorySlug, product.category])).entries()]
  .map(([slug, name], index) => ({ slug, name, sortOrder: (index + 1) * 10 }))
  .sort((left, right) => left.slug.localeCompare(right.slug));

const duplicateRateConfigurations = quotationVariants.filter((variant, index, variants) => variants.findIndex((candidate) => (
  candidate.productId === variant.productId
  && candidate.materialClass === variant.materialClass
  && candidate.thickness === variant.thickness
  && candidate.size === variant.size
  && candidate.lamination === variant.lamination
)) !== index);

if (duplicateRateConfigurations.length) {
  throw new Error(`Cannot create bootstrap migration: ${duplicateRateConfigurations.length} duplicate rate-card configurations were found.`);
}

const categorySql = rows(categories.map((category) => `(${value(category.name)}, ${value(category.slug)}, ${value(`Initial V2 catalogue group for ${category.name}.`)}, ${category.sortOrder}, 'published')`));

const productSql = catalogue.map((product) => {
  const specifications = {
    category: product.category,
    categorySlug: product.categorySlug,
    family: product.family,
    imageUrl: product.image,
    idealFor: product.idealFor,
    availableForms: product.availableForms,
    selectionNotes: product.selectionNotes,
    technicalData: product.technicalData || [],
    technicalDataNote: product.technicalDataNote || "",
  };
  const quotationEnabled = ["xlpe-sheet-insulation", "xlpe-tube-insulation", "nitrile-rubber-sheet", "nitrile-rubber-tube", "insulation-adhesive", "insulation-tapes"].includes(product.slug);
  const featured = ["nitrile-rubber-sheet", "xlpe-sheet-insulation", "xlpe-underdeck-insulation", "foil-bubble-insulation", "rock-wool-slab", "glass-wool-acoustic-board"].includes(product.slug);
  return `insert into public.products (category_id, name, slug, short_description, description, material, key_benefits, specifications, status, published_at, quotation_enabled, featured, active)
select categories.id, ${value(product.name)}, ${value(product.slug)}, ${value(product.shortDescription)}, ${value(product.overview)}, ${value(product.family)}, ${json(product.keyBenefits)}, ${json(specifications)}, 'published', now(), ${quotationEnabled}, ${featured}, true
from public.categories as categories where categories.slug = ${value(product.categorySlug)}
on conflict (slug) do update set
  category_id = excluded.category_id,
  name = excluded.name,
  short_description = excluded.short_description,
  description = excluded.description,
  material = excluded.material,
  key_benefits = excluded.key_benefits,
  specifications = excluded.specifications,
  status = excluded.status,
  published_at = excluded.published_at,
  quotation_enabled = excluded.quotation_enabled,
  featured = excluded.featured,
  active = excluded.active;`;
}).join("\n\n");

const rateSql = rows(quotationVariants.map((variant) => `(${value(variant.productId)}, ${value(variant.materialClass)}, ${value(variant.thickness)}, ${value(variant.size)}, ${value(variant.lamination)}, ${value(variant.orderUnit)}, ${value(variant.rate)}, ${value(variant.rateUnit)}, ${value(variant.rollAreaM2)}, ${value(variant.packRunningMetres)}, ${value(variant.orderUnit === "carton" ? `${variant.packTubes || 1} tubes / carton` : variant.orderUnit === "drum" ? `${variant.packLitres || 1} L / drum` : variant.packUnitLabel || null)}, 1, 18, true, null, null, ${value("Initial V2 governed rate-card load")}, now())`));

const sql = `-- Generated by scripts/generate-supabase-bootstrap.ts. Do not edit by hand.
-- This is the one-time V2 production catalogue and governed rate-card baseline.
-- Product count: ${catalogue.length}; rate-card count: ${quotationVariants.length}.

insert into public.categories (name, slug, description, sort_order, status)
values
${categorySql}
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  sort_order = excluded.sort_order,
  status = excluded.status;

${productSql}

insert into public.quotation_rate_cards (
  product_slug, material_class, thickness, size_label, lamination, order_unit,
  rate, rate_unit, roll_area_m2, pack_running_metres, packing_label, moq,
  gst_rate, active, valid_from, valid_to, reason, published_at
)
values
${rateSql}
on conflict (product_slug, material_class, thickness, size_label, lamination) do update set
  order_unit = excluded.order_unit,
  rate = excluded.rate,
  rate_unit = excluded.rate_unit,
  roll_area_m2 = excluded.roll_area_m2,
  pack_running_metres = excluded.pack_running_metres,
  packing_label = excluded.packing_label,
  moq = excluded.moq,
  gst_rate = excluded.gst_rate,
  active = excluded.active,
  valid_from = excluded.valid_from,
  valid_to = excluded.valid_to,
  reason = excluded.reason,
  published_at = excluded.published_at;

insert into public.quotation_rate_card_history (rate_card_id, old_rate, new_rate, valid_from, valid_to, reason)
select cards.id, null, cards.rate, cards.valid_from, cards.valid_to, 'Initial V2 governed rate-card load'
from public.quotation_rate_cards as cards
where cards.reason = 'Initial V2 governed rate-card load'
  and not exists (
    select 1 from public.quotation_rate_card_history as history
    where history.rate_card_id = cards.id
  );
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, sql, "utf8");
console.log(`Generated ${outputPath} with ${catalogue.length} products and ${quotationVariants.length} rate cards.`);
